### ISSUE TITLE
Throw TypeError when new an object extends Proxy object

### ISSUE THREAD

**Issue by sunlili** [Microsoft/ChakraCore#5523] opened 2018-07-25 12:56 UTC
Hi,
The following code behaves incorrectly (inconsistent with other engines).
```
new class extends new Proxy(class {},{}) {}
```
In ChakraCore, the output is
`TypeError: Object doesn't support this action`

However, in V8 , SpiderMonkey and JSC, output is
`BT_FLAG`

BT group
2018.7.25

**Comment by MSLaguana** [comment] 2018-07-25 15:47
I believe that this is a duplicate of #5225 and has been fixed in master, but not in release/1.10. @sethbrenith do you think it's worth backporting to release/1.10?

**Comment by sethbrenith** [comment] 2018-07-25 15:52
Yes, I reopened #5225 to track backporting.

**Comment by kfarnung** [comment] 2018-07-26 00:00
Thanks for the report! We'll use #5225 to track the backport work.

**Closed by kfarnung** 2018-07-26 00:00 UTC
Labels: Bug, Duplicate
