### ISSUE TITLE
Intl.DateTimeFormat string comparison

### ISSUE THREAD

**Issue by nlkluth** [Microsoft/ChakraCore#1013] opened 2016-05-20 16:10 UTC
The resulting string from Intl.DateTimeFormat doesn't equal the string literal that I expect. This has some resulting different behavior from other browsers if I try to do any validation against the string. I know it's a new specification and I can polyfill it to get the behavior I want, but thought I should report it in case it's not on anyone's radar.

![capture](https://cloud.githubusercontent.com/assets/1868613/15434130/b3002806-1e72-11e6-806e-80b1a93e9b4b.PNG)

**Comment by goyakin** [comment] 2016-05-21 10:02
This is a duplicate of #599. Chakra's Intl formatting functions put [LEFT-TO-RIGHT MARK (U+200E)](http://www.fileformat.info/info/unicode/char/200e/index.htm) around punctuation marks and that's why the resulting string doesn't match the string literal.

**Comment by bterlson** [comment] 2016-05-21 11:07
Closing as duplicate.

**Closed by bterlson** 2016-05-21 11:07 UTC
