### ISSUE TITLE
Duplicate Symbol Keys in ES6 Map Possible (Sometimes, Randomly) if the Symbol was Obtained From Object.getOwnPropertySymbols

### ISSUE THREAD

**Issue by dwighthouse** [Microsoft/ChakraCore#5852] opened 2018-11-28 23:50 UTC
In Microsoft Edge (as of Edge 42.17134.1.0), if attempting to add the same Symbol as a key multiple times to an ES6 Map (via `set`), and IF AND ONLY IF that Symbol was obtained from its usage as one of a Object's keys (via `Object.getOwnPropertySymbols`), there is about a 70% chance that the Map will allow the second usage of the same key.

The mere fact that a given Symbol is somewhere used as one of an Object's keys does not cause the issue. The problem only seems to occur when getting the references to the Symbol from `Object.getOwnPropertySymbols`.

The issue doesn't always occur, but it is frequent. Perhaps it is a race condition. My 70% occurrence estimation is a rough feeling, not based on actual measurement.

I suspect that something in Edge's implementation of the Map's `set` function doesn't correctly check equality on Object keys when they are Symbols.

No other parts appear to be affected. Referencial Equality is maintained between all appropriate Symbol references after getting the duplicate keys back out of the Map, so it doesn't appear that Edge is somehow creating a new reference when using a Symbol as an Object key.

Here is a minimal set of test cases showing the issue, where it fails, and where it does not:
https://jsfiddle.net/s0qpdmyw/1/

**Comment by dwighthouse** [comment] 2018-11-28 23:54
Here are the examples in question, in case the link goes down:

```javascript
// Failure Case
(function() {
    const sharedSymbol = Symbol();

    const obj = {};

    obj[sharedSymbol] = 1;

    const box = new Map();
    box.set(Object.getOwnPropertySymbols(obj)[0], {});
    box.set(Object.getOwnPropertySymbols(obj)[0], {});

    const mapKeys = [];
    box.forEach((v, key) => {
        mapKeys.push(key);
    });

    const boxSize = box.size;

    console.log('Compare Map Key to Map Key (below should always be 1)');
    console.log(boxSize); // Sometimes 1, usually 2 in Microsoft Edge
    if (boxSize > 1) {
        console.log(mapKeys[0] === mapKeys[1]); // Is always true
        console.log(mapKeys[0] === sharedSymbol); // Is always true
        console.log(mapKeys[1] === sharedSymbol); // Is always true
    }
})();

// Failure Case
(function() {
    const sharedSymbol = Symbol();

    const obj = {};

    obj[sharedSymbol] = 1;

    const box = new Map();
    box.set(Object.getOwnPropertySymbols(obj)[0], {});
    box.set(sharedSymbol, {});

    const mapKeys = [];
    box.forEach((v, key) => {
        mapKeys.push(key);
    });

    const boxSize = box.size;

    console.log('Compare Map Key to Symbol (below should always be 1)');
    console.log(boxSize); // Sometimes 1, usually 2 in Microsoft Edge
    if (boxSize > 1) {
        console.log(mapKeys[0] === sharedSymbol); // Is always true
        console.log(mapKeys[1] === sharedSymbol); // Is always true
    }
})();
```

**Comment by dwighthouse** [comment] 2018-11-29 23:53
Found a small workaround.

Somehow, simply storing the `Object.getOwnPropertySymbols(obj)[0]` value into another variable before adding that to the Map, rather than adding the resulting Symbol value directly to the Map, causes Edge to never add the duplicate Symbol.

**Comment by dilijev** [comment] 2018-11-30 00:04
Can you confirm whether this is still an issue in the latest version of Edge?

**Comment by dilijev** [comment] 2018-11-30 00:21
Your example behaves the same in all engines.

```
eshost --tags jsvu-web -ts 5852.js

┌──────────┬───────────────────────────────────────────────────────┐
│ jsvu-ch  │ Compare Map Key to Map Key (below should always be 1) │
│ jsvu-jsc │ 1                                                     │
│ jsvu-sm  │ Compare Map Key to Symbol (below should always be 1)  │
│ jsvu-v8  │ 1                                                     │
└──────────┴───────────────────────────────────────────────────────┘
```

It looks like this has been fixed since ChakraCore 1.10

```
#### ch-1.8-latest, ch-1.9-latest
Compare Map Key to Map Key (below should always be 1)
2
true
true
true
Compare Map Key to Symbol (below should always be 1)
2
true
true

#### ch-1.10-latest, ch-1.11-latest, ch-master-latest
Compare Map Key to Map Key (below should always be 1)
1
Compare Map Key to Symbol (below should always be 1)
1
```

**Comment by liminzhu** [comment] 2018-11-30 00:26
I can confirm both cases return 1 in EdgeHTML 18.17763, so yeah, fixed in the latest version.

**Closed** 2018-11-30 00:51 UTC
Labels: Bug, Fixed, Severity: 2

**Comment by dwighthouse** [comment] 2018-11-30 00:59
Oh! How strange. I thought Edge was an Evergreen browser.

Wait... I have all Windows 10 updates installed ("You're up to date; Last checked: Today, 6:55PM"), but Edge is still reporting that it is version 42.17134.1.0 (EdgeHTML 17.17134).

Stupid question: Why do I not have the latest version of Edge, and how can I get it?

**Comment by dilijev** [comment] 2018-12-02 19:31
@dwighthouse clarifying further -- We use "evergreen" to mean the latest version of the browser is biased toward the modern web rather than compatibility with old web (in contrast to IE's interest in being compatible with every previous version of the browser and anything that was ever on the web).
