### ISSUE TITLE
Regex replace with proxied function attempts to stringify proxy instead of call it

### ISSUE THREAD

**Issue by sunlili** [Microsoft/ChakraCore#5509] opened 2018-07-24 08:14 UTC
Hello,
The following code behaves strangely (inconsistent with other engines).
```
checkNaN('b', 'a'.replace(/a/, new Proxy(() => 'b', {})));

if(!isNaN(Math.pow()))
{
    print("error: Math.pow() is not NaN");
}
print("done");

function check(result, x, y) {
    var rs = Math.pow(x, y);
    if ( Math.abs(rs - result) > 0.00000000001) {
        print("pow(" + x + " , " + y + ") != " + result);
        print(" wrong result is pow(" + x + " , " + y + ") = " + rs);
    }
}

function checkNaN(x, y) {
    var rs = Math.pow(x, y);
    if (!isNaN(rs)) {
        print("pow(" + x + " , " + y + ") !=  NaN" );
        print(" wrong result is pow(" + x + " , " + y + ") = " + rs);
    }
}
print("BT_FLAG");
```

In ChakraCore, the output is
`TypeError: Function.prototype.toString: 'this' is not a Function object`

However, in V8, SpiderMonkey and JSC, output is
```
done
BT_FLAG
```

BT group
2018.7.24

**Comment by MSLaguana** [comment] 2018-07-24 15:58
I believe that this is the same issue as https://github.com/Microsoft/ChakraCore/issues/5479 where we don't detect a proxied function as callable.

**Comment by kfarnung** [comment] 2018-07-25 23:58
Narrowed down the repro to just:

```javascript
print('a'.replace(/a/, new Proxy(() => 'b', {})));
```

Closing as a duplicate of #5479.

**Closed by kfarnung** 2018-07-25 23:58 UTC
Labels: Duplicate
