### ISSUE TITLE
"Function expected" error when using spread syntax on a NodeList to convert it to array

### ISSUE THREAD

**Issue by chrisrollins** [Microsoft/ChakraCore#3759] opened 2017-09-19 05:31 UTC
Example:

let arr = [...document.querySelectorAll("*")]

This throws the error, "Function expected"

**Comment by akroshg** [comment] 2017-09-19 16:52
@chrisrollins thanks for reporting the issue.
This is not a chakracore issue. The support for iterating dom objects have added in RS3 this will be ship soon.
This issue seems dupe of #3229

**Comment by chrisrollins** [comment] 2017-09-19 19:30
@akroshg Where should I report JavaScript issues I find in the Edge browser?

**Comment by digitalinfinity** [comment] 2017-09-19 19:35
Hi @chrisrollins thanks again for reporting the issue. In general, if it's a JS issue, this is the right place. However, if it involves the DOM (e.g document.querySelectorAll), it could be an Edge issue instead, in which case we'll redirect you to their bug tracker (For more details, see https://github.com/Microsoft/ChakraCore/wiki/External-Issues). 

In this case, it looks like this should be fixed when the next release of Windows ships. You should be able to confirm on a recent Windows Insiders flight (you can install these preview builds using the instructions at https://insider.windows.com/en-us/how-to-pc/).

**Comment by digitalinfinity** [comment] 2017-09-19 19:36
@akroshg please correct me if I'm wrong about the availability of this fix on recent preview builds

**Comment by akroshg** [comment] 2017-09-19 20:21
@digitalinfinity yes this is available in the recent preview builds.

**Closed** 2017-09-21 21:12 UTC
Labels: External, Fixed
