### ISSUE TITLE
ES6 constructor erring with object doesn't support this action

### ISSUE THREAD

**Issue by Quethrosar** [Microsoft/ChakraCore#1011] opened 2016-05-19 17:10 UTC
the following code is throwing     object doesn't support this action on the this.Key.
it runs fine for about 30 seconds and then starts erring. this error only happens in Edge.

class Value {
        constructor(key, data) {
            this.Key = key;
            this.Data = data;
        }
    }

**Comment by abchatra** [comment] 2016-05-19 17:51
@Quethrosar What version of Edge are you using?

**Comment by Quethrosar** [comment] 2016-05-19 19:49
25.10586.0.0
13.10586

I am going to attach the script that I have issues with. 

[jquery.signalR-2.2.0.zip](https://github.com/Microsoft/ChakraCore/files/273357/jquery.signalR-2.2.0.zip)

**Comment by Quethrosar** [comment] 2016-05-19 19:54
another hint is if I compile the typescript using ES3 it runs but edge will hit memory in the GB range overnight, where chrome will be 90mb. the memory profiler shows no leaks at only using a few MB.

**Comment by abchatra** [comment] 2016-05-19 21:48
@Quethrosar is there a glue html code which can be run on the browser to reproduce this problem using the script you attached here? My hunch is this problem is already fixed in later versions of Edge, but would love to validate the problem go away.

**Comment by abchatra** [comment] 2016-05-19 21:49
Small test case would be awesome

**Comment by dilijev** [comment] 2016-06-14 23:14
@Quethrosar do you have the corresponding HTML so we could verify whether this issue still exists?

**Comment by EdMaurer** [comment] 2016-09-07 21:33
Closing due to lengthy inactivity and incomplete repro.

**Closed by EdMaurer** 2016-09-07 21:33 UTC
Labels: Bug
