### ISSUE TITLE
null pointer dereference in JavascriptExceptionOperators::OP_TryCatch

### ISSUE THREAD

**Issue by zhiyi01** [microsoft/ChakraCore#6307] opened 2019-10-11 08:04 UTC
This `test.js` can trigger null pointer dereference .
run `ch.exe -bgjit- test.js`
```javascript
const v4 = [13.37, 13.37];

function v8() {
    const v15 = Math.round(Infinity);
    try {
        v8();
        const v19 = new Uint32Array();
        const v20 = typeof v19;

    } catch (v20) {
        v4.d = 1;
    }
}

v8();
```
Version :  v1.11.14
OS :  Win10

**Comment by akroshg** [comment] 2019-10-11 17:30
This does not repro on master branch but reproes on release/1.11 (and below) branch. I haven't debugged the test to tell what is the cause of the problem.

**Comment by akroshg** [comment] 2019-10-11 22:21
This issue was fixed in the master branch 8 months back.
I have cherry picked 87b168a2e391d0338c661f8b7c661202bc09b91c to bring this change to release/1.11 branch

**Closed** 2019-10-11 22:21 UTC
