### ISSUE TITLE
Edge not execute scripts if there are many module scripts

### ISSUE THREAD

**Issue by magic-akari** [Microsoft/ChakraCore#5986] opened 2019-03-02 04:49 UTC
If there are many module scripts `<script type="module">` in the web page, Edge will load these scripts but not execute them.

## Edge version
- Edge 44.17763.1.0
- EdgeHTML 18.17763

## Minimal reproducible example 
https://gist.github.com/5fe16e41e153c2c41575c88ee1bea778.git

## Steps
open the page and devtools, check the console output.

## Expected behavior
screenshot from Chrome:

![image](https://user-images.githubusercontent.com/7829098/53677311-be0b4680-3ce8-11e9-855c-b4fa6a4d0876.png)

## Actual behavior
screenshot from Edge:

![image](https://user-images.githubusercontent.com/7829098/53677334-2b1edc00-3ce9-11e9-81be-d09bcb271e1c.PNG)

My page impacted by this issue: https://magic-akari.github.io/lrc-maker

**Comment by rhuanjl** [comment] 2019-03-05 18:10
I’ve tested CC with many more modules than this; looking at the example this is probably a circular imports problem and a duplicate of #5236

**Comment by MikeHolman** [comment] 2019-03-05 20:11
Thanks @rhuanjl for looking. Closing this and upping the severity of the existing bug.

**Closed by MikeHolman** 2019-03-05 20:11 UTC
