### ISSUE TITLE
Intl functions shouldn't be constructible

### ISSUE THREAD

**Issue by goyakin** [Microsoft/ChakraCore#637] opened 2016-03-23 23:57 UTC
According to the [spec](https://tc39.github.io/ecma262/#sec-built-in-function-objects):

> Built-in function objects that are not identified as constructors do not implement the [[Construct]] internal method unless otherwise specified in the description of a particular function

Since our Intl functions are script functions (implemented in `Intl.js`), they are constructible by default. For example,

``` JS
new Intl.Collator.prototype.compare
```

causes the error:

> TypeError: Collator.prototype.compare: 'this' is not a Collator object

instead of:

> TypeError: Function is not a constructor

**Comment by dilijev** [comment] 2017-02-04 02:02
@bterlson pointed me toward this discussion https://github.com/tc39/ecma402/issues/57

**Comment by ljharb** [comment] 2017-02-04 02:06
Could they be implemented as arrow functions, or do they need access to `this`?

**Comment by dilijev** [comment] 2017-02-04 02:33
Unsure. I'll need to understand the spec and the linked discussion a bit better first.

**Comment by dilijev** [comment] 2017-02-04 02:33
For myself for future reference: [Intl documentation on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Collator/compare)

**Comment by dilijev** [comment] 2017-09-05 23:21
Not a functionality bug per se because we emit the correct kind of error, but the message is perhaps misleading. Adding Dev Experience and unassigning myself for now.

**Comment by jackhorton** [comment] 2017-12-22 17:41
Was playing around with this a bit -- in chakra, anonymous function expressions bound to variables don't take the name of their variables (unlike at least in SpiderMonkey), so my initial belief on turning this into arrow functions is that the best error message we could get is "Function is not a constructor", rather than "getCanonicalLocales is not a constructor". @bterlson thoughts on if thats good enough?

**Comment by bterlson** [comment] 2017-12-22 19:08
> in chakra, anonymous function expressions bound to variables don't take the name of their variables (unlike at least in SpiderMonkey),

It seems like we do the right thing (`let thing = () => {}; thing.name;` => "thing"). If we're not doing this it's likely a bug... where are you seeing this behavior?

> @bterlson thoughts on if thats good enough?

not good enough, but our errors messages generally need help. "Function is not a constructor" is in the family of "object is null or undefined" though, in that it isn't particularly helpful.

**Comment by jackhorton** [comment] 2017-12-23 06:19
![image](https://user-images.githubusercontent.com/4370013/34317534-d5668e2c-e765-11e7-9093-e54464472480.png)

Seems like this should be fixable. Also interestingly, we _definitely_ don't set the name property of normal function expressions assigned to variables, even though we do set the name of lambdas assigned to variables. I just confirmed this again locally but ran into it in Intl.js before.

**Comment by bterlson** [comment] 2017-12-28 18:57
See also: https://github.com/Microsoft/ChakraCore/issues/3407.

**Closed** 2018-08-28 15:50 UTC
Labels: Bug, Dev Experience, Intl, Severity: 2
