### ISSUE TITLE
ScriptTerminated error not returned

### ISSUE THREAD

**Issue by dennis-yemelyanov** [Microsoft/ChakraCore#5134] opened 2018-05-11 01:56 UTC
After disabling runtime execution the script completes successfully with no error, although I expect ScriptTerminated to be returned. This seems to be happening only when the script has no other commands to execute after runtime execution is disabled. For example, when I try this script, the error is printed as expected (here 'sleep' is a custom callback function that simply does Thread.Sleep, and another thread disables runtime execution after 1 second):
`string script = "(()=>{sleep(2000); return new Date();})()";`

Output:
```
Error code: ScriptTerminated
Return value:
```
But if the script returns a simple string, it completes successfully and no error is returned:
`string script = "(()=>{sleep(2000); return \'Hello world!\';})()";`

Output:
```
Error code: NoError
Return value: Hello world!
```

Is there a way to get a ScriptTerminated error from the script executed in the second example?

**Comment by fatcerberus** [comment] 2018-05-11 06:28
If runtime execution is disabled *after* the script has already finished ("has no other commands to execute", as you say), why would you expect an error?  It indeed completed successfully.  I wouldn't want to be the person that has to debug time-traveling errors... 😝

**Comment by dennis-yemelyanov** [comment] 2018-05-11 06:44
I guess that depends on whether "return" statement should be considered as a separate command?

In the second example I would expect all execution to stop and "return 'Hello world!'" to never be executed, and an error to be returned instead (similarly to the first example, which has no return value, but has an error).

**Comment by fatcerberus** [comment] 2018-05-11 06:48
Stopping runtime execution does depend on hitting designated breakpoints in the bytecode; I don’t remember where this is documented but I know it’s documented somewhere.  It’s probably just that `new Date()` causes such a breakpoint to be injected while the bare `return` doesn’t.

**Comment by fatcerberus** [comment] 2018-05-11 06:51
Found it:
https://github.com/Microsoft/ChakraCore/wiki/JavaScript-Runtime-%28JSRT%29-Overview#runtime-resource-usage

> Because script termination depends on reaching guard points inserted into the code, a script may not terminate at the exact moment, but will do so very shortly afterwards.

“Shortly afterwards” in your second case just happens to be “after it’s already completed”.

**Comment by dennis-yemelyanov** [comment] 2018-05-11 07:14
Thanks! Yeah I've seen this page before and I actually pass JsRuntimeAttributeAllowScriptInterrupt, but looks like it's not enough to cover this scenario. I guess this behavior does align with the documentation... Maybe there is really no reason for the runtime to treat a `return` specially. In the worst case I could probably add some meaningless operation right before the `return`, which would guarantee a breakpoint :)

**Comment by fatcerberus** [comment] 2018-05-11 14:31
AllowScriptInterrupt from what I understand just adds a few extra guards in loops so that you don’t get stuck in an infinite loop.  You wouldn’t want one after every instruction or your code would run insanely slowly.

**Comment by liminzhu** [comment] 2018-05-12 00:31
@dennis-yemelyanov curious is there any reason you want termination to happen at a specific line? The common use case for resource management that the host shuts things down once a certain CPU/time threshold is crossed, in which case you don't really care which specific line of code termination happens.

**Comment by dennis-yemelyanov** [comment] 2018-05-12 01:37
Thanks @liminzhu. In my case termination can be user-initiated, so if some command takes longer than expected and the user decides to cancel, I thought it would be nice to stop right after that command. But now I understand why it might not be possible without slowing the script down, and I think it makes sense.

**Comment by liminzhu** [comment] 2018-05-12 03:06
Thanks for sharing!

**Comment by liminzhu** [comment] 2018-05-12 03:08
Seems like the issue is resolved so I'm closing it, but feel free to re-open if you have any other issue with this.

**Closed by liminzhu** 2018-05-12 03:08 UTC
