### ISSUE TITLE
JsCreateContext in a new thread sometimes fail with JsErrorOutOfMemory

### ISSUE THREAD

**Issue by bytenull** [Microsoft/ChakraCore#3700] opened 2017-09-11 13:26 UTC
On linux (Mint 17.03)
GCC 4.8.4
Kernel 4.2.0-25
Testing with 9.4 GB of free memory.

I compiled ChakraCore from source (with all dependencies already installed)
"git clone https://github.com/Microsoft/ChakraCore.git"
"./build.sh -j=4 --target=linux --with-intl"

I also tried the pre built library. Downloaded from azure with the same results.

The following program reproduce the problem randomly. The lower the amount of threads the less likely the issue is to manifest itself, with 100 threads the odds are about 1 in 10 execution of the program. I've encountered the problem with a thread count as low as 10.
```
void* ContextCreationTest(void * p_param) {
	JsRuntimeHandle runtime;
	JsContextRef context;
	JsErrorCode err;
	err = JsCreateRuntime(JsRuntimeAttributeNone,nullptr,&runtime);
	if(err != JsNoError) {
		cout << "runtime creation error " << hex << err << endl;
		return nullptr;
	}

	err = JsCreateContext(runtime,&context);
	JsDisposeRuntime(runtime);
	if(err != JsNoError)
		cout << "context creation error " << hex << err << endl;
	return nullptr;
}

int main() {
	int nbThreads = 100;
	pthread_t threads[nbThreads];
	for(auto i = 0 ; i < nbThreads; ++i) {
		pthread_create(&threads[i],nullptr,&ContextCreationTest,nullptr);
	}
	void* threadReturn;
	for(auto i = 0 ; i < nbThreads; ++i) {
		pthread_join(threads[i],&threadReturn);
	}
	return 0;
}
```

**Comment by obastemur** [comment] 2017-09-11 15:00
I'm unable to reproduce. Could you share `ulimit -a` output?

**Comment by bytenull** [comment] 2017-09-11 15:03
Certainly.
```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 63394
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 63394
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

**Comment by obastemur** [comment] 2017-09-11 16:10
@bytenull Thanks for reporting this. Finally reproduced. I will be looking into it.

**Comment by bytenull** [comment] 2017-09-11 16:36
After more testing,  a cheap workaround is just calling JsCreateContext again. I've never seen it failed twice in a row.
```
	int nbTryLeft = 3;
	do {
		err = JsCreateContext(runtime,&context);
		--nbTryLeft;
	}
	while(err == JsErrorOutOfMemory && nbTryLeft > 0);
```

This is not ideal, however in my application I did not see further unexpected behavior once the context is created (so far).

@obastemur Thanks for looking into it.

**Comment by obastemur** [comment] 2017-09-12 16:12
@bytenull looks like, on my end, when the number of open threads reach to 2048, I receive the error (out of memory) and it comes from pthread. That's the reason for `500 threads always reproduce`.

I'm not sure what we can do here but some more info for you.

Each time you create a new context/thread, you will have +2 (or more) additional threads. ChakraCore uses them for background tasks and/or GC. So, when you push 500 threads, you actually trigger the creation of ~1500 to ~2000 threads. Based on the system configs etc. you have a limited stack memory and each and every thread consumes some of it. That's why you receive out of memory. 

My suggestion is that make sure the previous thread/context was closed prior to opening a new one and expect the process may not have any free stack memory left.

I'm going to close this for now.

**Comment by bytenull** [comment] 2017-09-12 18:27
@obastemur thanks for investigating, however as stated I've had the error come up with just 10 threads on a freshly started process. Consider this revised test, it reproduce the error consistently (on my system at least) with a low thread count.

If there was a resource leak from pthread at some point the main would no longer be able to create threads. And when I comment everything in ContextCreationTest beside the return nullptr the program terminate without any issues with pthread_create.

I understand that I am over simplifying the problem, but I do not think it's a resource problem.

I'll try rebuilding on fresh ubuntu 16.04 server and see.

Here is the output of the test on my machine

```
context creation error 20001 iteration 1
context creation error 20001 iteration 22
context creation error 20001 iteration 53
context creation error 20001 iteration 76
context creation error 20001 iteration 85
context creation error 20001 iteration 91
context creation error 20001 iteration 102
context creation error 20001 iteration 110
context creation error 20001 iteration 123
context creation error 20001 iteration 123
context creation error 20001 iteration 141
context creation error 20001 iteration 200
context creation error 20001 iteration 288
context creation error 20001 iteration 291
context creation error 20001 iteration 334
context creation error 20001 iteration 341
context creation error 20001 iteration 343
context creation error 20001 iteration 405
context creation error 20001 iteration 451
```

```
void* ContextCreationTest(void * p_param) {
	JsRuntimeHandle runtime;
	JsContextRef context;
	JsErrorCode err;
	err = JsCreateRuntime(JsRuntimeAttributeNone,nullptr,&runtime);
	if(err != JsNoError) {
		cout << "runtime creation error " << hex << err << endl;
		return nullptr;
	}

	err = JsCreateContext(runtime,&context);
	JsDisposeRuntime(runtime);
	if(err != JsNoError)
		cout << "context creation error " << hex << err << " iteration " << dec << *(int*)p_param << endl;
	return nullptr;
}

int main() {
	int maxIteration = 500;
	int nbThreads = 10;

	for(int iteration = 0; iteration < maxIteration; ++iteration) {
		pthread_t threads[nbThreads];
		for(auto i = 0 ; i < nbThreads; ++i) {
			if(pthread_create(&threads[i],nullptr,&ContextCreationTest,&iteration) != 0) {
				cout << "pthread_create failed";
				return 0;
			}
		}
		void* threadReturn;
		for(auto i = 0 ; i < nbThreads; ++i) {
			pthread_join(threads[i],&threadReturn);
		}
	}
	return 0;
}
```

**Comment by obastemur** [comment] 2017-09-13 00:54
As I mentioned above a bit, the problem is the number of helper threads. They are not closed at the same time. I re-opened this issue to see if we might improve the things around for a use case like yours.

**Comment by fatcerberus** [comment] 2017-09-25 05:32
> As I mentioned above a bit, the problem is the number of helper threads. They are not closed at the same time.

@obastemur Is the above the reason I get a `JsErrorWrongThread` error on Unix platforms when destroying and then immediately creating a new runtime/context pair?  I should note that the aforementioned shutdown/init cycle works fine in Windows, but not in Linux or macOS.

**Comment by obastemur** [comment] 2017-09-25 10:37
@fatcerberus runtime model is a bit different among ChakraCore Windows and *nix. Is it reasonable to assume that on your use case, aprox. 10 CC threads are up at a time?

**Comment by fatcerberus** [comment] 2017-09-25 13:20
No, miniSphere is single-threaded.  There is only ever one runtime/context pair at any given time and it’s only accessed by a single thread.

**Comment by fatcerberus** [comment] 2017-09-25 13:23
@obastemur Additional note on above: The JsErrorWrongThread error for me is 100% reproducible, happening every single time I destroy the runtime/context and then recreate them.  There is never a case where sometimes it succeeds and sometimes not, which indicates it’s not a race condition.

**Comment by obastemur** [comment] 2017-09-25 14:26
> Additional note on above: The JsErrorWrongThread error for me is 100% reproducible, 

@fatcerberus We are still talking about the same problem, right? The one you got was related to `stack memory starvation`. Do you have another case that you receive `JsErrorWrongThread` (with a single thread)? OR, (as you mentioned) you always have max 1 active thread at a time and you still got this error?

**Comment by fatcerberus** [comment] 2017-09-25 14:31
@obastemur Sorry for the confusion, the OP had a different issue, I just wondered if mine was related to the same root cause.

**Comment by obastemur** [comment] 2017-09-25 14:34
Yes, your issue is not the same. You might want to destroy the use a separate thread for the second runtime? Please file a separate issue and lets see how we can improve the experience there.

**Comment by obastemur** [comment] 2017-11-11 00:20
I was looking at worker threads and saw that we create decent amount of GC threads; https://github.com/Microsoft/ChakraCore/blob/e70038a64d9a009e68e0762753ede95d78e116a8/lib/Common/Memory/Recycler.cpp#L870 

..number of threads per instance follows;

Worker ) cpuCount - 2
GC        ) cpuCount > 4 ? 4 : cpuCount

So, if you have a `4 cores` setup, you will endup with `6` extra threads.

**Comment by obastemur** [comment] 2017-11-11 00:34
And Unfortunately I'm unable to repro an issue here apart from file handler starvation after a good amount of run. 

Also on your outputs, the error code 20001 comes from `pthread`... So, closing this again :/

**Closed by obastemur** 2017-11-11 00:34 UTC
Labels: By Design
