### ISSUE TITLE
Classes extending null should bind a 'this' value

### ISSUE THREAD

**Issue by tcare** [Microsoft/ChakraCore#2294] opened 2016-12-29 01:24 UTC
class Foo extends null { constructor() {} };

new Foo(); // use-before-decl, should not throw

See tc39/test262#813 and https://github.com/tc39/ecma262/issues/543#issuecomment-210191577

**Comment by dilijev** [comment] 2016-12-31 01:44
Duplicate of #829

**Closed by dilijev** 2016-12-31 01:44 UTC
Labels: Bug, ES Spec Changed
