### ISSUE TITLE
Regex causes ChakraCore to exit process

### ISSUE THREAD

**Issue by rodrigoamicrosoft** [Microsoft/ChakraCore#4538] opened 2018-01-12 00:16 UTC
Calling RunScript on the following JavaScript causes ChakraCore to exit the process, no exception is thrown. If "x2|" is removed from the regex the issue does not repro. This script works correctly on Chakra.dll

var f = function (x) { var str = " droid24gP xh06build/"; var reg = /\s(milestone|droid(?:[2-4x]|\s(?:bionic|x2|pro|razr))?(:?\s4g)?)[\w\s]+build\//i; return str.search(reg); }

**Comment by jackhorton** [comment] 2018-01-16 16:54
@dilijev ?

**Comment by dilijev** [comment] 2018-01-17 02:47
@rodrigoamicrosoft which version of ChakraCore.dll are you using? (And for completeness re: version of Chakra.dll which build of Windows are you on? i.e. as seen from `winver`)

Are you hosting ChakraCore.dll and just calling RunScript on that snippet? Did you then attempt to call the function you created or did it crash first? Can you repro in any version of ch.exe?

The closest thing I have to a repro of this behavior is an overzealous FailFast (which would intentionally crash ch.exe as we considered a certain regex compilation path to be a fatal unrecoverable state). This logic was only problematic in certain versions of release/1.8 between 2017-10 and 2017-12. No version of release/1.7 had this issue with overzealous FailFast.

We have since fixed the underlying issue so that this FailFast check should not fire anymore. The latest builds from release/1.8 would not have this issue, if this FailFast is the root cause.

The AssertOrFailFast was added here: https://github.com/Microsoft/ChakraCore/pull/3924
Logic fixed in: https://github.com/Microsoft/ChakraCore/issues/4411

cc @Penguinwizzard

**Comment by dilijev** [comment] 2018-01-17 02:51
Removed External Contributor tag because this is not a PR.

**Comment by dilijev** [comment] 2018-01-17 20:40
Sounds like this is either fixed (FailFast mentioned above) or repros only in ChakraCore.dll (not Chakra.dll), so not a priority for release/1.8. I will continue to investigate and, if deemed a high priority, will escalate.

**Comment by dilijev** [comment] 2018-02-12 19:10
@rodrigoamicrosoft could you confirm whether your issue repros in the latest builds?

**Comment by dilijev** [comment] 2018-06-07 00:05
@rodrigoamicrosoft Feel free to reopen this issue if you confirm that this still repros.

**Closed by dilijev** 2018-06-07 00:05 UTC
Labels: Bug, No Repro, Severity: 2, Waiting
