### ISSUE TITLE
ES6 class name not set when defined in window object

### ISSUE THREAD

**Issue by lbuchs** [Microsoft/ChakraCore#5672] opened 2018-09-07 10:36 UTC
When defining a class with ES6, if you define the class in the window object, the class name is not set:

```
    <script>
        test1 = class Foo {};
        window.test2 = class Bar {};
        
        console.log(window.test1.name);
        console.log(window.test2.name);   
    </script>
```

Expected output:
```
Foo
Bar
```

Actual output:
```
Foo

```

Tested in Microsoft Edge 42.17134.1.0 / EdgeHTML 17.17134

**Comment by sethbrenith** [comment] 2018-09-07 14:56
Thanks for the report! I can reproduce this issue on Edge 42 but not Edge 44 (insiders preview version), so it looks like this bug is already fixed in the upcoming version.

**Closed by sethbrenith** 2018-09-07 14:56 UTC
