### ISSUE TITLE
Chakra failed when build with permissive- by msvc on Windows

### ISSUE THREAD

**Issue by QuellaZhang** [Microsoft/ChakraCore#5947] opened 2019-02-14 10:07 UTC
Chakra failed with lots of errors when build with permissive- by msvc on Windows, I use latest source version c95f834 on master branch. Could you please help take a look at this? Noted that this issue only found when compiles with unreleased vctoolset, that next release of MSVC will have this behavior.

**You can repro this issue as the steps below:**

1. git clone -c core.autocrlf=true https://github.com/microsoft/ChakraCore D:\Chakra\src
2. open a clean x86 prompt (C:\windows\syswow64\cmd.exe) and browse to D:\Chakra\src
3. set CL=/permissive- /d1ParseTrees:identErrors-
4. msbuild /m /p:Platform=x86 /p:Configuration=Test /p:WindowsTargetPlatformVersion=10.0.17134.0 Build\Chakra.Core.sln /t:Rebuild

**Failures:**
D:\Chakra\src\lib\SCACore\SCADeserialization.h(53,36): error C2760: syntax error: unexpected token '<', expected 'declaration'
            typedef TypedArrayTrace<T,clamped> trace_type;
                                   ^
D:\Chakra\src\lib\SCACore\SCADeserialization.h(53,36): note: This diagnostic occurred in the compiler generated function 'void Js::DeserializationCloner<Reader>::ReadTypedArray(TDst *) const'
            typedef TypedArrayTrace<T,clamped> trace_type;
                                   ^
D:\Chakra\src\lib\SCACore\SCADeserialization.h(162): note: see reference to class template instantiation 'Js::DeserializationCloner<Reader>' being compiled
    };
D:\Chakra\src\lib\SCACore\SCASerialization.h(47,36): error C2760: syntax error: unexpected token '<', expected 'declaration'
            typedef TypedArrayTrace<T, clamped, isVirtual> trace_type;
                                   ^
D:\Chakra\src\lib\SCACore\SCASerialization.h(47,36): note: This diagnostic occurred in the compiler generated function 'void Js::SerializationCloner<Writer>::WriteTypedArray(TSrc) const'
            typedef TypedArrayTrace<T, clamped, isVirtual> trace_type;
                                   ^
D:\Chakra\src\lib\SCACore\SCASerialization.h(187): note: see reference to class template instantiation 'Js::SerializationCloner<Writer>' being compiled
    };

**Comment by fatcerberus** [comment] 2019-02-22 01:40
You've posted this same issue several times.  Duplicate of #5813 (among others).

See this comment in #5813:
> we don't support building with `/permissive-` or unreleased toolsets, but we are happy to merge fixes for issues like this if you would like to submit a patch.

**Closed** 2019-03-02 01:32 UTC
Labels: Codebase Quality, Duplicate
