### ISSUE TITLE
Chakra should throw SyntaxError when declaring function twice with "use strict"

### ISSUE THREAD

**Issue by baac** [Microsoft/ChakraCore#5453] opened 2018-07-12 14:26 UTC
Hi everyone, 
I would like to report an issue when using "use strict" and declaring a function twice on same scope the others engines raises a SyntaxError, maybe this issue is a dupe of #5076.

Chakra: 1.10.1
OS: Ubuntu 16.04 x86

Steps to reproduce:
```
function test() {
  "use strict";
  function f() {
     return 1;
  }
  {
     function f() {
        return 2;
     }
     function f() {
        return 3;
     }
  }
  return f() === 1;
}
if (!test())
  throw new Error("Test failed");
```
Actual results:
pass without failures

Expected results:
SyntaxError: redeclaration of function

SpiderMonkey, V8 and JavaScriptCore works as expected.

**Comment by kfarnung** [comment] 2018-07-12 20:11
Confirmed in eshost:

```
#### V8, V8 --harmony
SyntaxError: Identifier 'f' has already been declared

#### JavaScriptCore
SyntaxError: Cannot declare a function that shadows a let/const/class/function variable 'f' in strict mode.

#### Chakra


#### SpiderMonkey
SyntaxError: redeclaration of function f:
```

@dilijev @VSadov Is this the same as #5076?

**Comment by kfarnung** [comment] 2018-07-14 02:04
Closing as duplicate of #5076, thanks for the report @baac!

**Closed by kfarnung** 2018-07-14 02:04 UTC
Labels: Bug, Severity: 3
