### ISSUE TITLE
Multiple characters not treated as valid variable part

### ISSUE THREAD

**Issue by hackvertor** [Microsoft/ChakraCore#3271] opened 2017-06-30 08:39 UTC
```javascript
eval('_'+String.fromCharCode(1320)+'_=alert(1)')
```
Expected: alert function to be called and variable assigned

Actual: Invalid character exception

Every other browser treats the characters as a valid variable part. The following characters are also treated incorrectly.

895,1320,1321,1322,1323,1324,1325,1326,1327,2209,2221,2222,2223,2224,2225,2226,2303,2424,2432,3072,3124,3201,3329,3558,3559,3560,3561,3562,3563,3564,3565,3566,3567,5873,5874,5875,5876,5877,5878,5879,5880,6158,6429,6430,6832,6833,6834,6835,6836,6837,6838,6839,6840,6841,6842,6843,6844,6845,7416,7417,7655,7656,7657,7658,7659,7660,7661,7662,7663,7664,7665,7666,7667,7668,7669,42648,42649,42650,42651,42652,42653,42900,42901,42902,42903,42904,42905,42906,42907,42908,42909,42910,42911,42923,42924,42925,42928,42929,42999,43488,43489,43490,43491,43492,43493,43494,43495,43496,43497,43498,43499,43500,43501,43502,43503,43504,43505,43506,43507,43508,43509,43510,43511,43512,43513,43514,43515,43516,43517,43518,43644,43645,43646,43647,43824,43825,43826,43827,43828,43829,43830,43831,43832,43833,43834,43835,43836,43837,43838,43839,43840,43841,43842,43843,43844,43845,43846,43847,43848,43849,43850,43851,43852,43853,43854,43855,43856,43857,43858,43859,43860,43861,43862,43863,43864,43865,43866,43868,43869,43870,43871,43876,43877,65063,65064,65065,65066,65067,65068,65069

**Comment by dilijev** [comment] 2017-07-11 22:25
eshost repro:

`eshost -its -e "eval('_'+String.fromCharCode(1320)+'_=print(1)')"`

**Comment by dilijev** [comment] 2017-07-11 22:26
Duplicate of #1208 
Related: #3050

**Closed by dilijev** 2017-07-11 22:26 UTC
Labels: Bug, Duplicate
