### ISSUE TITLE
Create a lot of instances - error Object doesn't support property or method 'Add'

### ISSUE THREAD

**Issue by viktorspacil** [Microsoft/ChakraCore#1583] opened 2016-09-15 09:01 UTC
Dear Madam/Sir,
we experienced following problem in the Edge web browser (v14.14393). We are using JavaScript ES6 (converted from TypeScript) in our web application and when we create a lot of instances of any class (for example 200-300 instances) then we receive error Object doesn't support property or method 'Add' which does not make sense to us. This functionality works fine in other tested browsers (Google Chrome, Mozilla Firefox). Thank you for fixing this bug.

Run JS file in the attachment to reproduce the bug. 
[EdgeBugTestCase.zip](https://github.com/Microsoft/ChakraCore/files/474188/EdgeBugTestCase.zip)

**Comment by obastemur** [comment] 2016-09-15 10:38
After replacing DOM references to dummy JS objects, this issue is not reproducible as a CH terminal app. [ + increased loop from 1000 to 1e6, still no issue ]

**Comment by ianwjhalliday** [comment] 2016-09-15 13:15
@suwc could this be the same or related to #1496?

**Comment by viktorspacil** [comment] 2016-09-15 13:46
Modified test case without DOM references uploaded:
[EdgeBugTestCase.zip](https://github.com/Microsoft/ChakraCore/files/474775/EdgeBugTestCase.zip)

The bug was successfully reproduced in version 14.14393 and 14.14915 of the Edge web browser.

**Comment by suwc** [comment] 2016-09-15 17:21
@ianwjhalliday, you are right - this is a duplicate of #1496.

**Comment by viktorspacil** [comment] 2016-09-15 18:32
#1496 seems to be the same problem like ours

**Comment by dilijev** [comment] 2016-09-19 19:34
Closing as Duplicate.

**Closed by dilijev** 2016-09-19 19:34 UTC
Labels: Bug, Duplicate
