### ISSUE TITLE
Incorrect realization of Array.prototype.push

### ISSUE THREAD

**Issue by sunlili** [Microsoft/ChakraCore#5611] opened 2018-08-20 12:41 UTC
Hi, following code behaves different from other JS engines.
```
function test0() {
    var GiantPrintArray = []; 
    function v9870() {
        try {
            var arr = []; 
            var v9872 = []; 
            let rlt = Object.defineProperty(Array.prototype, "0", 
                    {   
                        configurable: true, 
                        get: function () {
                            print("in get"); 
                            return 30; 
                        }   
                    }); 
            GiantPrintArray.push(-1);                                                                                                                                                                             
        }   
        catch(ex) {
            print(ex.message);
        }   
    }   
    v9870();
    print(GiantPrintArray[0]);
};
test0();
print("BT_FLAG");
```

In ChakraCore(ch version 1.10.0.0), the output is
```
-1
BT_FLAG
```
However, since setter is not defined, the exception message should be printed. Other JS engines' output :
```
setting getter-only property 0
in get
30
BT_FLAG
```
BT group
2018.8.20

**Comment by zenparsing** [comment] 2018-08-23 15:49
Yes, this is a duplicate of #5033.

The set operation should fail when it encounters an accessor property for `Array.prototype.0` with no setter. `Array.prototype.push` is specified to throw if the set operation fails.

**Closed** 2018-08-23 17:47 UTC
Labels: Bug, Duplicate, Severity: 3
