### ISSUE TITLE
Vars should not hoist past lets.

### ISSUE THREAD

**Issue by bterlson** [Microsoft/ChakraCore#850] opened 2016-04-21 18:46 UTC
```js
{
  let x;
  {
    var x;
   }
}
print(x);
```

Expected: Error, x undeclared.
Actual: prints undefined as the var binding hoists past let.

**Comment by ianwjhalliday** [comment] 2016-08-26 20:07
Just noticed this is a duplicate of an issue I opened earlier. #357

**Closed by ianwjhalliday** 2016-08-26 20:07 UTC
Labels: Bug
