### ISSUE TITLE
string representation of floats larger than 2^53 differs from other engines

### ISSUE THREAD

**Issue by sunlili** [Microsoft/ChakraCore#5363] opened 2018-06-25 08:48 UTC
Hello,
The following code behaves incorrectly (inconsistent with the standard and other engines).
ch version 1.8.5.0
```
var nonArray=({                                                                                                                                                      
    length:4,
    0:42,
    2:37,
    0xf7da5000:undefined,
    0x8000000000000800:0
});
Array.prototype.sort.call(nonArray);

print(JSON.stringify(nonArray));
print("BT_FLAG");
```

The output is:
{"0":37,"1":42,"length":4,"9223372036854777000":0}
BT_FLAG

However, other engines' output are:
{"0":37,"1":42,"length":4,"9223372036854778000":0}
BT_FLAG

BT group
2018.6.25

**Comment by zenparsing** [comment] 2018-06-25 16:14
Minimum repro:

```js
print(0x8000000000000800);
```

**Comment by rhuanjl** [comment] 2018-06-25 16:16
Possibly a duplicate of this issue https://github.com/Microsoft/ChakraCore/issues/149

**Closed** 2018-06-26 01:13 UTC
Labels: Duplicate
