### ISSUE TITLE
Argument deconstruction and default assignment broken for functions with more than one argument

### ISSUE THREAD

**Issue by KrofDrakula** [Microsoft/ChakraCore#4998] opened 2018-04-17 09:55 UTC
Arrow functions argument deconstruction seems to exhibit a bug with deconstructing arguments with default values when the first argument isn't deconstructed. It works so long as the first argument is deconstructed with a default value, else all subsequent deconstructions will not allow setting a default value to the argument.

Here's an example that works:

```
(function({ a = 1 }, { b = 2 }) { return a + b; })({}, {}); // returns 3
(function(x = 4, { a = 1 }, { b = 2 }) { return a + b; })(undefined, {}, {}); // returns 3
(function({ a = 1 }, x = 4, { b = 2 }) { return a + b; })({}, undefined, {}); // returns 3
(function({ a = 1 }, { b = 2 }, x = 4) { return a + b; })({}, {}, undefined); // returns 3
```

Here's the same example with arrow functions:

```
(({ a = 1 }, { b = 2 }) => a + b)({}, {}); // returns 3
((x = 4, { a = 1 }, { b = 2 }) => a + b)(undefined, {}, {}); // should return 3, instead throws "Expected ':'"
(({ a = 1 }, x = 4, { b = 2 }) => a + b)({}, undefined, {}); // returns 3
(({ a = 1 }, { b = 2 }, x = 4) => a + b)({}, {}, undefined); // returns 3
```

Removing **both** default assignments for destructuring in the second arrow function example fixes the problem:

```
((x, { a }, { b }) => a + b)(undefined, {}, {}); // returns NaN, as expected
```

**Comment by sethbrenith** [comment] 2018-04-17 13:48
Thanks for the report! This sounds like #4919, do you agree?

**Comment by sethbrenith** [comment] 2018-04-17 15:34
closing as duplicate of #4919

**Closed by sethbrenith** 2018-04-17 15:34 UTC
