### ISSUE TITLE
test/benchmarks/Octane/typescript.js segmentation fault

### ISSUE THREAD

**Issue by cosinusoidally** [Microsoft/ChakraCore#2302] opened 2017-01-02 01:09 UTC
I built ChakraCore on Linux (Ubuntu 16.04) as per the instructions here: https://github.com/Microsoft/ChakraCore/wiki/Building-ChakraCore/da4ffbc0ac4598f211fee4fb40b6657210b84ac1

I was on the master branch (dce349e3192fcebd9f8d889c858a60845f7a12bd). This issue occurred on Test and Release builds. I was unable to test on a Debug build as Debug builds could not run the test case in a reasonable amount of time.

Build flags:
```
./build.sh -t -j 2
```
When running the typescript.js benchmark I get a segfault:
```
root@ljw-VirtualBox:~/ChakraCore/BuildLinux/Test# ./ch  /root/ChakraCore/test/benchmarks/Octane/typescript.js 
Segmentation fault (core dumped)
root@ljw-VirtualBox:~/ChakraCore/BuildLinux/Test# time ./ch  /root/ChakraCore/test/benchmarks/Octane/typescript.js 
Segmentation fault (core dumped)

real	0m27.314s
user	0m28.100s
sys	0m4.852s
root@ljw-VirtualBox:~/ChakraCore/BuildLinux/Test# time ./ch  /root/ChakraCore/test/benchmarks/Octane/typescript.js 
Segmentation fault (core dumped)

real	0m6.953s
user	0m8.760s
sys	0m2.708s
root@ljw-VirtualBox:~/ChakraCore/BuildLinux/Test# time ./ch  /root/ChakraCore/test/benchmarks/Octane/typescript.js 
Segmentation fault (core dumped)

real	0m21.995s
user	0m21.972s
sys	0m4.328s
```

Note it segfaults after different amounts of time.

When I run with `-GCMemoryThreshold:512` the segfault goes away:
```
root@ljw-VirtualBox:~/ChakraCore/BuildLinux/Test# ./ch -GCMemoryThreshold:512 /root/ChakraCore/test/benchmarks/Octane/typescript.js 
### SCORE: 16364
```
I ran `ch` under  gdb but it seems to crash in different places each run:

```
root@ljw-VirtualBox:~/ChakraCore/BuildLinux/Test# gdb ./ch 
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.04) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./ch...(no debugging symbols found)...done.
(gdb) run  /root/ChakraCore/test/benchmarks/Octane/typescript.js
Starting program: /root/ChakraCore/BuildLinux/Test/ch /root/ChakraCore/test/benchmarks/Octane/typescript.js
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff5f1f700 (LWP 7461)]
[New Thread 0x7ff7f1c99700 (LWP 7462)]


Thread 1 "ch" received signal SIGSEGV, Segmentation fault.
0x00007ffff4f9c438 in Js::JavascriptFunction::DeferredParseCore(Js::ScriptFunction**, int&) () from /root/ChakraCore/BuildLinux/Test/libChakraCore.so
(gdb) 
(gdb) backtrace 
#0  0x00007ffff4f9c438 in Js::JavascriptFunction::DeferredParseCore(Js::ScriptFunction**, int&) ()
   from /root/ChakraCore/BuildLinux/Test/libChakraCore.so
#1  0x00007ffff4f9c411 in Js::JavascriptFunction::DeferredParse(Js::ScriptFunction**) () from /root/ChakraCore/BuildLinux/Test/libChakraCore.so
#2  0x00007ffff510b430 in Js::JavascriptFunction::DeferredParsingThunk(Js::RecyclableObject*, Js::CallInfo, ...) ()
   from /root/ChakraCore/BuildLinux/Test/libChakraCore.so
#3  0x00007ff7e65aa729 in ?? ()
#4  0x00007fffffff55f0 in ?? ()
#5  0x0000000010000001 in ?? ()
#6  0x00007ff7f1cd0020 in ?? ()
#7  0x000100007fe0fd2b in ?? ()
#8  0x0001000000000000 in ?? ()
#9  0x00007ff7f1cd88e0 in ?? ()
#10 0x0001000000000000 in ?? ()
#11 0x0000000000000000 in ?? ()
(gdb) run  /root/ChakraCore/test/benchmarks/Octane/typescript.js
The program being debugged has been started already.
Start it from the beginning? (y or n) y
Starting program: /root/ChakraCore/BuildLinux/Test/ch /root/ChakraCore/test/benchmarks/Octane/typescript.js
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff5f1f700 (LWP 7482)]
[New Thread 0x7ff7f1c99700 (LWP 7483)]

Thread 1 "ch" received signal SIGSEGV, Segmentation fault.
0x00007ffff4f9c438 in Js::JavascriptFunction::DeferredParseCore(Js::ScriptFunction**, int&) () from /root/ChakraCore/BuildLinux/Test/libChakraCore.so
(gdb) backtrace 
#0  0x00007ffff4f9c438 in Js::JavascriptFunction::DeferredParseCore(Js::ScriptFunction**, int&) ()
   from /root/ChakraCore/BuildLinux/Test/libChakraCore.so
#1  0x00007ffff4f9c411 in Js::JavascriptFunction::DeferredParse(Js::ScriptFunction**) () from /root/ChakraCore/BuildLinux/Test/libChakraCore.so
#2  0x00007ffff510b430 in Js::JavascriptFunction::DeferredParsingThunk(Js::RecyclableObject*, Js::CallInfo, ...) ()
   from /root/ChakraCore/BuildLinux/Test/libChakraCore.so
#3  0x00007ff7e9f77aaa in ?? ()
#4  0x00007fffffff7848 in ?? ()
#5  0x0000000002000001 in ?? ()
#6  0x00007ff7f1cd0020 in ?? ()
#7  0x000100007fe0fc22 in ?? ()
#8  0x0001000000000000 in ?? ()
#9  0x00007ff7f1cd88e0 in ?? ()
#10 0x00007ff7f1cd8900 in ?? ()
#11 0x0000000000000000 in ?? ()
(gdb) run  /root/ChakraCore/test/benchmarks/Octane/typescript.js
The program being debugged has been started already.
Start it from the beginning? (y or n) y
Starting program: /root/ChakraCore/BuildLinux/Test/ch /root/ChakraCore/test/benchmarks/Octane/typescript.js
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff5f1f700 (LWP 7485)]
[New Thread 0x7ff7f1c99700 (LWP 7486)]

Thread 1 "ch" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) backtrace 
#0  0x0000000000000000 in ?? ()
#1  0x00007ff7e8ed0af7 in ?? ()
#2  0x00007fffffff3c40 in ?? ()
#3  0x0000000010000001 in ?? ()
#4  0x00007ff7f1cd0020 in ?? ()
#5  0x00007ffff4e754b6 in Js::InterpreterStackFrame::InterpreterHelper(Js::ScriptFunction*, Js::ArgumentReader, void*, void*, bool) ()
   from /root/ChakraCore/BuildLinux/Test/libChakraCore.so
#6  0x00007ffff510b2fe in amd64_CallFunction () from /root/ChakraCore/BuildLinux/Test/libChakraCore.so
#7  0x00007ffff4e84cdc in Js::InterpreterStackFrame::ProcessUnprofiled() () from /root/ChakraCore/BuildLinux/Test/libChakraCore.so
#8  0x00007ffff4e75a3f in Js::InterpreterStackFrame::Process() () from /root/ChakraCore/BuildLinux/Test/libChakraCore.so
#9  0x00007ffff4e752d8 in Js::InterpreterStackFrame::InterpreterHelper(Js::ScriptFunction*, Js::ArgumentReader, void*, void*, bool) ()
   from /root/ChakraCore/BuildLinux/Test/libChakraCore.so
#10 0x00007ffff4e74d41 in Js::InterpreterStackFrame::InterpreterThunk(Js::JavascriptCallStackLayout*) ()
   from /root/ChakraCore/BuildLinux/Test/libChakraCore.so
#11 0x00007ff7f143905a in ?? ()
#12 0x00007fffffff41e0 in ?? ()
#13 0x00007ffff510b2fe in amd64_CallFunction () from /root/ChakraCore/BuildLinux/Test/libChakraCore.so
Backtrace stopped: frame did not save the PC
(gdb) 
```

**Comment by obastemur** [comment] 2017-01-02 01:40
@cosinusoidally Thanks for the report. /cc @leirocks IIRC you were mentioning this on one of the emails recently.

**Comment by digitalinfinity** [comment] 2017-01-03 01:16
@pleath redeferral related?

**Comment by liminzhu** [comment] 2017-01-30 19:26
@pleath iirc this is fixed a couple of weeks ago?

**Comment by pleath** [comment] 2017-01-30 19:30
Is it passing now? The issue came up over the holidays, and I didn’t see it at the time.

-- Paul

**Comment by liminzhu** [comment] 2017-01-30 20:35
@pleath may be worth checking again. I just remembered we did something for typescript.js two weeks ago so I thought this was the issue.

**Comment by liminzhu** [comment] 2017-01-30 21:26
I just built master and run typescript.js on Linux and it was working fine. Maybe it was something you already fixed with re-deferral @pleath ?

**Comment by MikeHolman** [comment] 2017-03-03 09:58
Can we close this? Sounds like it's fixed.

**Comment by cosinusoidally** [comment] 2017-03-03 12:04
Do you have some kind of automated regression test suite that you run on each branch (similar to Mozilla's Treeherder)? If so, wouldn't it be green if this was fixed?

**Comment by dilijev** [comment] 2017-04-25 03:50
@cosinusoidally yes, we have a regression suite (that's what lives under test/* mentioned in this bug report).

It looks like this issue is fixed. If that's not true, someone will open a new issue, or someone can comment on this issue with their repro.

Closing as fixed.

**Closed by dilijev** 2017-04-25 03:50 UTC
Labels: Bug
