### ISSUE TITLE
1.8 - Assert fail on export class with static methods

### ISSUE THREAD

**Issue by rhuanjl** [Microsoft/ChakraCore#4586] opened 2018-01-21 10:39 UTC
Found an issue that doesn't appear to effect release builds at all but does hit an assert in the debug build of the current 1.8 or master.

The below code was made by simplifying some real world code (removing sections 1 at a time until the assertion stopped occurring then putting lines back etc.)

The original code runs fine in a release build - this cut down version obviously shouldn't do anything it loads a module that exports a class with some static fields but nothing is called.

The assert this hits is here:
https://github.com/Microsoft/ChakraCore/blob/master/lib/Runtime/Language/JavascriptOperators.cpp#L6975

The comparison it's doing is size of slot array = 2 (in this case) > ScopeSlots::FirstSlotIndex which is also 2.

Issue was initially found by @fatcerberus I've just simplified the test case.

```js
//test.js
WScript.LoadScriptFile("mod1.js","module");
```

```js
//mod1.js
export class test
{
	static a()
	{

	}
	b()
	{
		test.a();
	}
}
```
Note - every element of that test case seems to be necessary to hit the assert - the class has to be exported - and it has to contain a static method that is called from within another method.

I'm afraid I have no ideas as to the cause of this issue.

**Comment by fatcerberus** [comment] 2018-01-21 15:28
Permalink to the assert in question:
https://github.com/Microsoft/ChakraCore/blob/8ce21429d7757fb5203eacfafe3f4b7a4487de6b/lib/Runtime/Language/JavascriptOperators.cpp#L6975

**Comment by rhuanjl** [comment] 2018-01-23 00:23
Just noticed that this is the same assert (and possibly the same underlying issue) as this older issue:
https://github.com/Microsoft/ChakraCore/issues/2949

**Comment by dilijev** [comment] 2018-01-24 01:37
Ah -- @tcare do you also want to take a look at this one?

**Comment by tcare** [comment] 2018-01-24 01:49
This is a dupe of the other. I'll hopefully get to this in the next month, but I have higher pri bugs that will be addressed first.

**Comment by dilijev** [comment] 2018-01-24 06:56
Closing as duplicate.

**Closed by dilijev** 2018-01-24 06:56 UTC
Labels: Bug, Duplicate, Needs Triage
