### ISSUE TITLE
For some Intl function calls where getters are fired, debugger shows 2 calls.

### ISSUE THREAD

**Issue by atulkatti** [Microsoft/ChakraCore#3439] opened 2017-07-27 01:32 UTC
This may be a spec issue. However, showing 2 calls corresponding to one call in the user code might be misleading.

Run the following with "ch -Intl -debugLaunch"
```js
var options = { ca: "gregory", hour12: true, timeZone:"UTC" }; 
var dateFormat1 = new Intl.DateTimeFormat("en-US", options);    /**bp:resume('step_over');locals();**/
WScript.Echo("");  
var date1 = new Date(2000, 1, 1);
var date2 = dateFormat1.format(date1);                          /**bp:resume('step_over');locals();**/
WScript.Echo("");  
```
**Actual output:** 
     "functionCallsReturn": {
       "[get format returned]": "function <large string>",
       "[Intl.DateTimeFormat.prototype.format returned]": "string ‎2‎/‎1‎/‎2000"
**Expected output:**
     "functionCallsReturn": {
       "[Intl.DateTimeFormat.prototype.format returned]": "string ‎2‎/‎1‎/‎2000"

**Comment by dilijev** [comment] 2017-07-27 01:41
The suggested problem here is that perhaps we should not show
```
"[get format returned]": "function ",
```

However by spec, the `format` property is defined as a getter with name `get format`. Since the `.format` is in user code, the user code invoked the getter, and it makes sense that this is logged.

@bterlson

**Comment by dilijev** [comment] 2017-07-27 01:43
Removing the Bug label for now until we can confirm that this is a Bug.

**Comment by bterlson** [comment] 2017-07-30 07:23
Sorry for ignorance in advance, but where is this logging coming from? It may be that whatever is doing the logging should exclude intrinsic getters? But yes, this is a getter so if this will log all getters I'd expect the actual output above.

**Comment by dilijev** [comment] 2017-07-31 01:03
This is coming from the ch debugger test output (run with `-debugLaunch`)

**Comment by dilijev** [comment] 2017-08-14 19:21
@atulkatti From @bterlson's comment, I think we can close this as it is not a bug. Do you agree?

**Closed** 2017-09-06 07:27 UTC
Labels: ECMAScript Spec, Needs Triage
