### ISSUE TITLE
BUG: Dynamic import should only return a rejected promise if it fails loading a module

### ISSUE THREAD

**Issue by rwaldron** [Microsoft/ChakraCore#5796] opened 2018-10-25 20:28 UTC
Test: https://github.com/tc39/test262/blob/master/test/language/expressions/dynamic-import/assignment-expression/unary-expr.js

Result: 

> Couldn't load file 'true'
> Couldn't load file 'undefined'
> Couldn't load file 'object'
> Couldn't load file 'NaN'
> Couldn't load file '-1'

Expected: every import call should return a promise that will be resolved/rejected at some later time. Presently, the import fails and produces these errors synchronously.

**Comment by rwaldron** [comment] 2018-10-25 20:33
Another: 

- https://github.com/tc39/test262/blob/master/test/language/expressions/dynamic-import/catch/nested-arrow-import-catch-eval-rqstd-abrupt-urierror.js

The correct error is produced, but not via a rejected promise, which is what it should do.

**Comment by rwaldron** [comment] 2018-10-25 20:48
There's a lot more of these, but I suspect that if it's fixed once all of these will pass.

**Comment by rhuanjl** [comment] 2018-10-25 21:22
In most of these cases the import() call is resulting in a promise that is rejected with the error as the reason BUT additionally ch prints to std whenever failing to load a module (or any file). You should note that execution of the script continues despite the printed exceptions.

That said this behaviour in ch is clearly not the most helpful and to disable it at the moment you'd have to supply the flag -MuteHostErrorMsg which also would disable printing exceptions thrown in normal code.

I could offer a PR to rework this so these module load errors are only printed when flag is supplied instead of the inverse - going to wait until some of my existing PRs are merged before opening another at the moment though.

**Comment by leobalter** [comment] 2018-10-26 14:46
@rhuanjl thanks for the information. 

@rwaldron in the meanwhile it might worth trying another run with this flag on to see if anything persists.

**Comment by rwaldron** [comment] 2018-10-26 15:04
As you said, adding `-MuteHostErrorMsg` to eshost's `ChakraAgent` args prevents the messages from being printed out, however these tests are still failing because the `import(...)` calls are not returning "promises that are eventually rejected" (with whatever error is produced by the module that `import(...)` attempted to import). 

Here's a thing I've just discovered: The tests that DO pass are those that fail before any file IO could possibly occur, eg: 

```js
const obj = {
    toString() {
        throw 'custom error';
    }
};

const f = async () => {
  await import(obj);
}

f().catch(error => {
  assert.sameValue(error, 'custom error');
}).then($DONE, $DONE);
```


So I know that the issue described here: https://github.com/Microsoft/ChakraCore/issues/5237 is still a problem, but `import('./cannot-find-this-file.js')` should be returning a promise that is rejected with some kind of error that indicates this module file isn't found, instead of just silent failure.

**Comment by rhuanjl** [comment] 2018-10-26 15:39
Ok looks there is a second bug in addition to the excess message printing I will investigate it.

**Comment by rhuanjl** [comment] 2018-10-26 17:43
I can't reproduce this second error, running with -ESDynamicImport -MuteHostErrorMsg

With this test:
```js
import ("./nonExistant.js").catch(e => print ("caught " + e));
```
I see:
caught URIError: ./nonExistant.js

Please can you point me to a specific case where the promise isn't rejected but should be?

**Closed** 2018-11-01 01:05 UTC
Labels: Bug
