### ISSUE TITLE
Implement Object.getOwnPropertyDescriptors

### ISSUE THREAD

**Issue by ljharb** [Microsoft/ChakraCore#254] opened 2016-02-03 16:51 UTC
[`Object.getOwnPropertyDescriptors`](https://github.com/tc39/proposal-object-getownpropertydescriptors) is stage 3. At this time, Webkit has implemented it and v8 has an open patch.

Would be a good first PR!

**Comment by ianwjhalliday** [comment] 2016-02-03 19:16
This is a bit beefy for a first pr, but a little help from folks familiar with `JavascriptLibrary.cpp` should be enough to get someone started.

**Comment by caitp** [comment] 2016-02-04 21:31
I've got a version locally, I'd be happy to help someone land it as their first PR

**Comment by nojvek** [comment] 2016-03-19 21:47
My chakra kungfu is very very basic. I just opened the project a couple of days ago.

I'm guessing the idea is to add an entry here

```
    void JavascriptLibrary::InitializeObjectConstructor(DynamicObject* objectConstructor, DeferredTypeHandlerBase * typeHandler, DeferredInitializeMode mode)
    {
```
 Is there a talk on how js functions are implemented in chakra? I'm trying to get the dots connected but haven't yet got it.

**Comment by caitp** [comment] 2016-03-19 23:33
It doesn't take too long to figure out --- basically figuring out where to implement the function, how to install the function on [%Object%](https://tc39.github.io/ecma262/#sec-object-constructor), and intuiting how to use the internal APIs to implement the basic case, without any fast paths for E.G. non-Proxy objects (which could easily be added in a followup).

**Comment by nojvek** [comment] 2016-03-20 00:14
Ha! I see the implementation of other PropertyDescriptor related magic is in JavascriptOperators.cpp.
Can I implement this in Intl.js or does this have to be implemented in CPP native?

What is the deciding factor on what goes in intl.js vs native cpp function?

What does Intl stand for anyway?

**Comment by ljharb** [comment] 2016-03-20 00:17
@nojvek "Internationalization"

**Comment by caitp** [comment] 2016-03-20 15:28
It isn't necessarily a good candidate for being self-hosted, due to most likely being polymorphic/megamorphic, and having improved access to the low level ops that are needed by the algorithm.

I would put this in JavascriptObject.cpp, with the other Object static methods

**Comment by ianwjhalliday** [comment] 2016-03-21 18:29
Yes, this function should be implemented on the `JavascriptObject` class following the pattern that the other Object APIs follow and it would be hooked up in `JavascriptLibrary::InitializeObjectConstructor()`.

There is no guide or formal documentation on the internals of how ChakraCore works.  We leave the codebase itself to be its own documentation.  Reading the code is the best way to learn how it works, but unfortunately I recognize this means there is a big learning curve for someone new.  Fortunately the built-in APIs are one of the more straightforward areas to pick up.

Follow the patterns you see with other example APIs.  E.g. take a look at `Object.getOwnPropertyDescriptor` implemented by `JavascriptObject::EntryGetOwnPropertyDescriptor`.  This is the entry point for the built-in API, the signature follows our JavaScript function calling convention, so the stack and parameters match a normal JavaScript function call.  By convention we prefix the C++ name of the implementing method of a JavaScript built-in with `Entry` to indicate this.  I.e. this new API should be named `JavascriptObject::EntryGetOwnPropertyDescriptors`.

Do a find in files of the various identifier names related to an example API to see all the places you need to touch when adding a new built-in API.

There are API tests under `test/es6` and `test/es7` for APIs introduced in ES6/7 that you can look at for examples of how to write a regression test for a built-in API. (ES7 here is not really a meaningful name since for example async functions missed ES 2016, but its the name we have been using to refer to post ES6 features).

Definitely go ahead and take a stab at this.  We welcome all constructive contribution and will actively help out for any questions that come up.

One note that right now we're in bug fixing lock down mode so this particular task won't be accepted directly into master in the short term.  We're working out the kinks on how to merge PRs for future work items and non-crticial bug fixes given our current internal workflow so please bear with us and have patience after submitting your PR.  We may approve the PR but leave it parked for a few weeks or we may merge it into a separate branch.  TBD.  Regardless, go ahead and submit a PR when you're ready and we'll review it promptly and let you know what our next step will be to get it merged in.

**Comment by ljharb** [comment] 2016-03-21 18:35
@ianwjhalliday :-/ that's sad to hear, since it has to be shipping in two browsers for a period of time before it can hit stage 4.

**Comment by ianwjhalliday** [comment] 2016-03-21 18:37
@ljharb agreed :(
cc @abchatra @bterlson

**Comment by bterlson** [comment] 2016-03-23 00:43
@ljharb Note that two browser impls is not explicitly required and in my opinion requiring two shipping browser implementations for this feature to be standardized is overkill assuming robust JS polyfill implementations are broadly used by this point.

**Comment by ljharb** [comment] 2016-03-23 06:02
@bterlson I agree, but I'd have thought the same about Object.values/entries, so I'm being conservative with this one.

**Comment by ljharb** [comment] 2016-06-10 20:32
This is now stage 4, and Edge is the last browser to implement this method. It'd be great if someone could jump on it :-)

**Comment by caitp** [comment] 2016-06-10 20:37
I can send a patch, but it would be great for someone else to take it. Maybe @thejoshwolfe would be interested.

**Comment by jordonwii** [comment] 2016-06-25 04:06
I've been looking to contribute to Chakra for awhile now, and this has been sitting here for almost equally long - can I take a stab at this for a first contribution?

**Comment by jordonwii** [comment] 2016-06-26 04:33
I went ahead and tried, anyway. :)

There were a few things I wasn't sure about, so I took a guess. Here's a few, if anyone knows the answer:
- What's the relationship between property *names*, property *IDs*, and property *keys*?
- What is HostDispatch and remote invocation?
- What's the best way to test a change like this?

Let me know if the PR is on the right track.

**Comment by ianwjhalliday** [comment] 2016-06-28 00:18
Apologies for the silence last week.  @jordonwii please do give this a whirl!

> - What's the relationship between property names, property IDs, and property keys?

Before the ES6 Symbol feature, property names could only be strings.  They could be any valid JavaScript string, but only strings. (Numeric indices are still considered strings in terms of the spec).

In our codebase, a PropertyId is the id number representing an interned string in a global PropertyID table.  I believe it is simply the index into this table.  Its purpose is to give fast identity checking on property names.  We can compare integers instead of doing string comparisons.  This is classical string interning.

Once the ES6 Symbol feature was introduced JavaScript could now have properties whose name was not a string, it was a distinct object, with no uniquely identifying string form.  This allows an object to have properties whose names cannot conflict with other names and can only be accessed via a handle to the symbol.

The terminology for property names has shifted to property keys to be less confusing and inclusive of both string names and symbol names.

In our codebase symbols get a PropertyId as well, to continue being easily identifiable and work seamlessly in our type system.  Note however they do not have a uniquely identifiable string name.  Instead they have an optional string description.  Care must be taken when converting a PropertyId to a string to make sure symbol PropertyIds are accounted for and handled differently.

Note you will also see PropertyRecord* in the codebase.  This is a pointer to the actual entry in the PropertyId table, and is also unique and can be used for fast identity checks of property names/keys.  There was once a desire to move to only using PropertyRecord*, but it wasn't fully realized, hence you'll see usage of both.

> - What is HostDispatch and remote invocation?

@Yongqu is best to answer this.

> - What's the best way to test a change like this?

Look at the unit tests under test\es6 or test\es5, and specifically look at the ones that test built-in APIs.  Generally we try to give full coverage of the specification, e.g. function object's .length property is correct, it and any other properties have the correct property attributes, the algorithm in the spec is tested for as many uniquely interesting classes of input cases that we can see, etc.

I recommend using the UnitTestFramework.js testing helper.  See example usage of it in the test\es6 tests.

**Comment by Yongqu** [comment] 2016-06-28 02:12
HostDispatch: We have COM interface pointer (IDispatch) based binding for Javascript objects came from trident. In general you don't need to worry about them too much as you can just use the normal object vtable methods. 
remote invocation, if we are thinking about the same thing, is for window.open style cross-process invocation that requires marshalling of Javascript objects. We have some invocation mechanism based on HostDispatch. Similar you are likely ok here. Sorry we are not open source the binding between chakra & edge at this time.

**Comment by jordonwii** [comment] 2016-06-28 17:30
I see. Thank you both for the explanations! I'll make some updates to the PR to incorporate that.

**Closed** 2016-07-08 22:44 UTC
Labels: Accepting PRs, Task, Your first PR
