### ISSUE TITLE
[JSRT]function comments does not match function signature

### ISSUE THREAD

**Issue by JohnMasen** [Microsoft/ChakraCore#4477] opened 2017-12-27 13:51 UTC
chakracore.h Ln77
The following 2 functions has incorrect XML comments.
1. Identical "summary","remarks" section
2. "params" does not match function declaration

```
/// <summary>
///     User implemented callback to get notification when the module is ready.
/// </summary>
/// <remarks>
/// Notify the host after ModuleDeclarationInstantiation step (15.2.1.1.6.4) is finished. If there was error in the process, exceptionVar
/// holds the exception. Otherwise the referencingModule is ready and the host should schedule execution afterwards.
/// </remarks>
/// <param name="referencingModule">The referencing module that have finished running ModuleDeclarationInstantiation step.</param>
/// <param name="exceptionVar">If nullptr, the module is successfully initialized and host should queue the execution job
///                           otherwise it's the exception object.</param>
/// <returns>
///     true if the operation succeeded, false otherwise.
/// </returns>
typedef JsErrorCode(CHAKRA_CALLBACK * FetchImportedModuleFromScriptCallBack)(_In_ JsSourceContext dwReferencingSourceContext, _In_ JsValueRef specifier, _Outptr_result_maybenull_ JsModuleRecord* dependentModuleRecord);

/// <summary>
///     User implemented callback to get notification when the module is ready.
/// </summary>
/// <remarks>
/// Notify the host after ModuleDeclarationInstantiation step (15.2.1.1.6.4) is finished. If there was error in the process, exceptionVar
/// holds the exception. Otherwise the referencingModule is ready and the host should schedule execution afterwards.
/// </remarks>
/// <param name="dwReferencingSourceContext">The referencing script that calls import()</param>
/// <param name="exceptionVar">If nullptr, the module is successfully initialized and host should queue the execution job
///                           otherwise it's the exception object.</param>
/// <returns>
///     true if the operation succeeded, false otherwise.
/// </returns>
typedef JsErrorCode(CHAKRA_CALLBACK * NotifyModuleReadyCallback)(_In_opt_ JsModuleRecord referencingModule, _In_opt_ JsValueRef exceptionVar);
```

**Comment by obastemur** [comment] 2017-12-27 14:38
Could you please send a PR?

**Comment by jackhorton** [comment] 2017-12-27 21:41
@obastemur John might not know what the correct summary and remarks should be here -- I know that at first glance, I don't know the difference between the two APIs. I think @liminzhu might be good to ping here.

**Comment by obastemur** [comment] 2017-12-27 23:42
> @obastemur John might not know what the correct summary

> "params" does not match function declaration

Reading the copy-paste above; 

- `dwReferencingSourceContext` and `referencingModule` above are declared in opposite places
- `specifier` and `dependentModuleRecord` are already explained on other module related docs in the same header file. i.e. https://github.com/Microsoft/ChakraCore/blob/master/lib/Jsrt/ChakraCore.h#L69-L70 

@JohnMasen spend some time in the module code hence might help?? on fixing the descriptions there.

**Comment by JohnMasen** [comment] 2017-12-29 06:44
@obastemur Thanks for your explanation, I’ve got my module running:)   Please feel free to close the bug when typos are fixed.

**Comment by obastemur** [comment] 2017-12-29 14:46
Happy to hear that. I thought you could send a PR for the typos though :) well, no worries if you can't!

**Comment by JohnMasen** [comment] 2017-12-30 02:38
I'm still a new guy in Git (used work with VSS and TFS ) . not sure how to create a PR in the repository which does not belongs to me. please change it from your side this time. Thanks:)

**Comment by dilijev** [comment] 2018-01-11 00:31
@JohnMasen now's as good a time to learn as any. We can walk you through it. You can ask for help on https://gitter.im/Microsoft/ChakraCore?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by rhuanjl** [comment] 2018-01-11 18:23
I previously wrote out the detail of this in answering the question in issue:
https://github.com/Microsoft/ChakraCore/issues/4324

https://github.com/Microsoft/ChakraCore/blob/master/lib/Jsrt/ChakraCore.h#L77-L89
Is accidentally a duplicate of the description of the next callback when it should actually be basically a duplicate of the one before it with minor tweaks, correct text would be something like this:
```
/// <summary>
///     User implemented callback to fetch modules imported from script e.g. when using dynamic import
/// </summary>
/// <remarks>
/// Notify the host to fetch the module requested by the script. This is the "import" part before HostResolveImportedModule in ES6 spec.
/// This notifies the host that a module should be imported, and the host needs to retrieve the module back.
/// </remarks>
/// <param name="dwReferencingSourceContext">The source context in which the import occurred.</param>
/// <param name="specifier">The specifier given for the module to be imported.</param>
/// <param name="dependentModuleRecord">The ModuleRecord of the module to be imported. If the module was requested before from other source, return the
///                           existing ModuleRecord, otherwise return a newly created ModuleRecord.</param>
/// <returns>
///     true if the operation succeeded, false otherwise.
/// </returns>
```

**Comment by liminzhu** [comment] 2018-01-19 22:48
Made a PR for this - https://github.com/Microsoft/ChakraCore/issues/3367

**Comment by liminzhu** [comment] 2018-01-23 01:17
Fixed by https://github.com/Microsoft/ChakraCore/pull/4581

**Closed by liminzhu** 2018-01-23 01:17 UTC
Labels: APIs, Dev Experience

**Comment by rhuanjl** [comment] 2018-01-23 20:16
Thanks for sorting this @liminzhu I'd meant to send a PR for this and completely forgot.
