### ISSUE TITLE
Inconsistent output compared with other JS engines when declare a function in try...catch

### ISSUE THREAD

**Issue by sunlili** [Microsoft/ChakraCore#5379] opened 2018-06-27 13:32 UTC
Hello,
The following code behaves strangely (inconsistent with other engines).
```
try {                                                                                                                                                                
    f0();
    function g(f0){
        f0();
    };  

}catch(g){}
g(()=>{print("hi");});
```
In Edge, output is
```hi```
However, in V8 and Firefox, output is
```TypeError: g is not a function```

BT group
2018.6.27

**Comment by zenparsing** [comment] 2018-06-27 15:22
I believe this is a duplicate of #5340

**Closed** 2018-06-27 23:06 UTC
Labels: Duplicate
