### ISSUE TITLE
Intl.DateTimeFormat incorrect formatting of date

### ISSUE THREAD

**Issue by oscar-b** [Microsoft/ChakraCore#1408] opened 2016-08-09 10:15 UTC
Compare the outputs from Chrome:

```
var date = new Date(Date.UTC(2012, 11, 20, 3, 0, 0));
var options = { weekday: 'short', month: 'numeric', day: 'numeric' };
console.log(new Intl.DateTimeFormat('en-US', options).format(date));
```

Chrome v51

```
Thu, 12/20
```

Edge 25.10586.0.0 EdgeHTML 13.10586

```
‎Thu‎, ‎12‎ ‎20
```

If you specify Swedish (sv-SE) locale it gets even worse in Edge:

```
‎tor‎ den ‎20‎ ‎12
```

Chrome: 

```
tors 20/12
```

I concider the output from Chrome to be more correct.

**Comment by dilijev** [comment] 2016-08-09 22:15
Confirmed differences with Edge 38.14393.0.0 EdgeHTML 14.14393, Chrome 52.0.2743.116, Chrome 54.0.2824.0-canary.

/cc @bterlson @digitalinfinity who may have context about Intl and standards.

**Comment by bterlson** [comment] 2016-08-09 22:57
From a standards perspective, we are free to provide whatever formats we find appropriate (so there is no guarantee of interoperability between different runtimes or the same runtime on different platforms for example). However, this output is clearly not correct :-P

**Comment by oscar-b** [comment] 2016-08-10 08:23
The missing `/` separator between day/month is clearly not correct, as you say. The Swedish locale that adds "den" is more debatable I guess, it's not wrong but it can get quite long compared to other locales. Most locales I could find doesn't use a word there (the form is more appropriate in running text).

**Comment by dilijev** [comment] 2016-08-10 08:32
@oscar-b Thanks for explaining the difference in form between running text and written dates. Makes sense. I think that the word choice is a globalization issue which is External to ChakraCore, but we will pass on the information to the right people. As for the missing slash, I think that might be something we can fix in ChakraCore (as it seems locale-independent).

Note: the separator `/` is also missing in locales which put the day before the month:

```
var date = new Date(Date.UTC(2012, 11, 20, 3, 0, 0));
var options = { weekday: 'short', month: 'numeric', day: 'numeric' };
console.log(new Intl.DateTimeFormat('fr-FR', options).format(date));
```

Chrome output: `mer. 19/12`
Edge output: `mer. 19 12`

**Comment by dilijev** [comment] 2016-11-14 21:49
Marking as External. As I previously mentioned, the word choice is a localization issue which is external to ChakraCore. We'll route this to the right people.

I'll look into the missing slash. Depending on whether that space or slash (depending on locale) is inserted by ChakraCore, this might also be a localization issue external to ChakraCore, or it might be something we can fix.

**Comment by dilijev** [comment] 2016-11-14 22:59
Unfortunately, even the absence of the slash seems to be entirely a localization issue external to ChakraCore. I will forward that information along to the right folks as well.

**Comment by dilijev** [comment] 2017-09-05 23:05
Relevant to ICU work #2919 
Closing because the issue is External to ChakraCore

**Closed by dilijev** 2017-09-05 23:05 UTC
Labels: Bug, External

**Comment by dilijev** [comment] 2017-09-05 23:52
Tracking in #3644
