### ISSUE TITLE
Assert failure while parsing child module

### ISSUE THREAD

**Issue by fatcerberus** [Microsoft/ChakraCore#3638] opened 2017-09-04 14:14 UTC
I tried using a debug build of ChakraCore to try to diagnose some crashes I've been seeing and found out that ChakraCore fails an assert during module parsing.  Upon calling `JsParseModuleSource()` for the first child module (the root module parses without issue), I get an assert failure here:
https://github.com/Microsoft/ChakraCore/blob/v1.7.1/lib/Runtime/Language/SourceTextModuleRecord.cpp#L698

**Comment by fatcerberus** [comment] 2017-09-04 15:07
If it helps at all, my module workflow is:
* Init module record and parse root module
* In FetchModule callback, init module record for child module and queue job to parse it
* Parse all child modules in a loop until queue is empty
* JsModuleEvaluation()

Best I can tell, this meets the requirements for async loading of modules, so no idea what's going wrong here.

**Comment by fatcerberus** [comment] 2017-09-05 04:09
The line in question looks to be checking whether the module record for the parent module was already registered, and does `Assert(false)` if it has.  I see no reason why that should be the case; the assertion triggers on the very first non-root module parsed, during this call:
https://github.com/fatcerberus/minisphere/blob/f688e1009cc91c4f51032b64f89150498caea96a/src/shared/jsal.c#L406-L408

**Comment by fatcerberus** [comment] 2017-09-05 13:51
the other other thing I could think of was that I was somehow creating duplicate module records, so I placed a breakpoint in my fetch module callback, but only one record is created for each filename.  So unless this is actually a Chakra bug, im completely stumped.

`ch` looks like it does exactly the same thing I do, so I tried to reproduce it there, but no matter what I did I couldn't get it to run any module code.  `ch -ES6Module module.mjs` just gives me back "import or export not expected here".  How do I get it to parse the script as a module?

**Comment by akroshg** [comment] 2017-09-05 17:07
Are you doing ```WScript.LoadModule(...)``` to load the root module code? You can search for usage under test\es6 folder (eg. test\es6\bug_issue_3247.js).
@suwc for the assert follow up.

**Comment by fatcerberus** [comment] 2017-09-05 17:24
I'm using the JSRT C API, so this is with `JsParseModuleSource()` directly, no WScript stuff involved.

**Comment by fatcerberus** [comment] 2017-10-01 19:41
This turned out to be that I was sometimes creating more than one module record for the same module; it seems that ChakraCore allows this in violation of the ES spec (see #3798) with the intent that the host handles it.  Since I *didn’t* handle it, I ended up triggering the assert because a module with the same name had already been created.

So problem solved - simple user error :)

**Comment by fatcerberus** [comment] 2017-10-12 03:34
Hm, nope, I'm still seeing this even after making sure not to load modules more than once.  I haven't been able to reproduce it with ch.exe yet sadly :(

**Comment by fatcerberus** [comment] 2017-10-12 13:56
The assertion being hit is this one:
https://github.com/Microsoft/ChakraCore/blob/70aae5a685a76768feb4492d6cc5eaea24a21db6/lib/Runtime/Language/SourceTextModuleRecord.cpp#L698-L699

I'm hitting that often after FetchImportedModuleCallback has been called only *once*, so this seems like it might be a bug in ChakraCore.  What's odd is that I can't reproduce it with ch.exe.

**Comment by fatcerberus** [comment] 2017-10-12 14:15
Okay, yeah, it looks like ChakraCore itself is setting the parent twice, triggering the assert.  This is a bug; **either the assert is incorrect, or the parent should only be set in one place.**  I'm not sure which is more appropriate, but one of those things has to be changed.

The first time the parent is set is in JsInitializeModuleRecord:
https://github.com/Microsoft/ChakraCore/blob/70aae5a685a76768feb4492d6cc5eaea24a21db6/lib/Jsrt/Core/JsrtCore.cpp#L32

SetParent then gets called *again* later, with the same module record and specifier pair, right after the FetchImportedModule callback:
https://github.com/Microsoft/ChakraCore/blob/70aae5a685a76768feb4492d6cc5eaea24a21db6/lib/Runtime/Language/SourceTextModuleRecord.cpp#L745

**Comment by digitalinfinity** [comment] 2017-12-07 04:22
@leirocks marked this for inclusion in 1.8, let me know if you disagree

**Comment by akroshg** [comment] 2018-01-11 23:18
@fatcerberus chakracore is calling the SetParent twice, that does not mean that it is setting it twice. In the SourceTextModuleRecord::SetParent you can see there is a check for 
```if (!parentRecord->childrenModuleSet->ContainsKey(moduleName)) ```

https://github.com/Microsoft/ChakraCore/blob/master/lib/Runtime/Language/SourceTextModuleRecord.cpp#L708

which will not succeed for the second time for the same module.
Without ch.exe repro it is hard to understand what went wrong. Is it possible that between modulename is changed between calls? Could you share a dump for me to get started?

**Comment by fatcerberus** [comment] 2018-01-11 23:22
The moduleName is the same both times, I’ve verified that in the debugger.  I’ll see if I can get more info later.

**Comment by fatcerberus** [comment] 2018-01-12 16:53
> Is it possible that between modulename is changed between calls?

I'm not sure how this is possible; the assert triggers during the execution of `JsParseModuleSource`--which doesn't take a module name.  The module name is passed to `JsInitializeModuleRecord` and there are no module-related calls in between so if the name has changed between calls, that sounds like a Chakra bug?

**Comment by fatcerberus** [comment] 2018-01-12 18:50
@akroshg I did some more debugging, it appears that the second SetParent call uses the moduleName verbatim from the source text (which is often relative), even though I initialize the module record using a fully normalized specifier.  This is why it's not reproducible in ch, because ch creates the module record using the un-normalized name and therefore the second SetParent is consistent with the first:
https://github.com/Microsoft/ChakraCore/blob/master/bin/ch/WScriptJsrt.cpp#L449

**Comment by akroshg** [comment] 2018-01-12 20:35
hmm, I have created a native test to break on this assert. I'll talk to @boingoing about why take name instead of module for the parent-child relationship. Also why we need to do the setparent twice? I'll revert back with more info later. Thanks,

**Comment by rhuanjl** [comment] 2018-01-23 20:18
So the assert was wrong and has now been removed - so technically the issue is fixed.

But we still have two different places with setParent calls which is wrong - see PR I've made to remove the incorrect one (actually the first one not the second one).

**Comment by rhuanjl** [comment] 2018-01-30 22:10
This issue has been fixed by #4548 and the related #4585 has also been merged should close this now.
@fatcerberus

**Comment by akroshg** [comment] 2018-01-30 22:30
Thanks @rhuanjl for making changes. Closing this issue.

**Closed by akroshg** 2018-01-30 22:30 UTC
Labels: Bug, Severity: 1
