### ISSUE TITLE
Destroying and then recreating a runtime/context fails with JsErrorWrongThread

### ISSUE THREAD

**Issue by fatcerberus** [Microsoft/ChakraCore#3797] opened 2017-09-25 14:41 UTC
The equivalent of the following pseudocode works in Windows but fails on *nix (at least Linux and macOS) with `JsErrorWrongThread`:
```c
// assuming a runtime and context were created a while ago...
JsSetCurrentContext(JS_INVALID_REFERENCE);
JsDisposeRuntime(runtime);
JsCreateRuntime(..., &runtime);  // this succeeds, but...
JsCreateContext(runtime, &context);  // this returns JsErrorWrongThread!
```

This happens for me even though my engine is single-threaded and the runtime/context is therefore never called from a different thread.  miniSphere has a function to restart the engine and I want to create a fresh runtime when that happens so that globals from the previous run don't leak into the new session.  This issue (is it a bug?) prevents that from working.

**Comment by obastemur** [comment] 2017-09-29 14:42
@jianchun I remember you were working on `on exit cleanup` stuff. Any comments on this issue?

**Comment by digitalinfinity** [comment] 2017-12-07 04:19
@obastemur @jianchun did either of you get a chance to look at whether this is a bug?

**Comment by jianchun** [comment] 2018-01-24 18:39
@obastemur @digitalinfinity I tried on Linux but could not reproduce this issue. Maybe timing or scripts run in the engine matters? 

@fatcerberus Apologize for late response. Any chance you could provide a repro?

**Comment by fatcerberus** [comment] 2018-01-24 18:53
@jianchun The issue turned out to be that I was `longjmp`ing out of a native function into `main()`.  I switched to calling `JsDisableRuntimeExecution()` to bail out instead and that fixed the problem.

**Comment by jianchun** [comment] 2018-01-24 22:33
@fatcerberus Thank you for the update! We just found an issue that could cause `JsDisableRuntimeExecution()` exit the process as in #4454. Will work on a fix for that. Closing this issue.

**Closed by jianchun** 2018-01-24 22:33 UTC
Labels: Question
