### ISSUE TITLE
Reflect.getPrototypeOf(TypeError) should return the Error prototype

### ISSUE THREAD

**Issue by gfablima** [Microsoft/ChakraCore#5065] opened 2018-04-30 01:05 UTC
Hi everyone,

when we try to get the prototype of an TypeError with Reflect.getPrototypeOf(TypeError) or Object.getPrototypeOf(TypeError) is expected that these functions should return the Error function.

OS: Ubuntu 16.04 x86
Chakra: 1.9

Step to reproduce:
```
var protoOfError = Reflect.getPrototypeOf(TypeError);
if (!(protoOfError === Error)){
  throw new Error('expected: function Error() {[native code]}, got: ' + protoOfError);
}
```
Actual results:
expected: function Error() {[native code]}, got: function () {[native code]}

Expected results:
pass without failures

Same occurs with RangeError, EvalError, ReferenceError, SyntaxError and URIError.

V8, SpiderMonkey and JavascriptCore work as expected.

**Comment by fatcerberus** [comment] 2018-04-30 05:01
```js
#/runtime/assert.mjs:33 module()
(ssj) e Reflect.getPrototypeOf(TypeError).toString()
= "function Error() { [native code] }"

#/runtime/assert.mjs:33 module()
(ssj) e Reflect.getPrototypeOf(TypeError) === Error
= true
```

Behavior looks correct to me.

**Comment by jackhorton** [comment] 2018-04-30 16:36
@gfablima , were you running this test using Node-ChakraCore? If so, I believe this may be caused by our monkey-patching of the error object in order to support custom V8 APIs.

**Comment by gfablima** [comment] 2018-05-01 23:02
I don't know if I'm running node-chakracore. I got the binary from master branch, running "./build.sh --static"

**Comment by digitalinfinity** [comment] 2018-05-02 03:46
It looks like this is controlled by the flag -ES6PrototypeChain which is defined as false in https://github.com/Microsoft/ChakraCore/blob/master/lib/Common/ConfigFlagsList.h#L613. I'm going to have to ask around as to why this is false- if I run `ch -ES6PrototypeChain test.js` the test behaves similar to other engines. Without that flag, error constructor functions are provided the function prototype as their prototypes.

**Comment by fatcerberus** [comment] 2018-05-02 03:48
Ah, that explains it: My runtime initialization includes `JsRuntimeAttributeEnableExperimentalFeatures` which presumably enables that flag (and, well, everything else).

**Comment by digitalinfinity** [comment] 2018-05-02 03:51
@fatcerberus that makes sense 😄 - I'll follow up on whether we can turn this on by default. @gfablima does @fatcerberus's pattern work for you?

**Comment by gfablima** [comment] 2018-05-02 21:20
Hi @fatcerberus and @digitalinfinity.
Thanks for this workaround, it works with the flag -ES6PrototypeChain

**Comment by digitalinfinity** [comment] 2018-08-01 00:43
Change is ready but the compat risk is high for 1.10- moving to vNext so that we have additional cushion for compat testing

**Closed** 2018-09-11 15:49 UTC
Labels: Bug, Severity: 2
