### ISSUE TITLE
(1d,P2) Intl-ICU: Custom management of ICU data lifetime (as resource, etc.)

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#3755] opened 2017-09-18 19:08 UTC
See http://userguide.icu-project.org/icudata

For now the workaround is to set `ICU_DATA` in the environment to the directory containing the ICU data .dat file (e.g. `icudt59l.dat`) to let ICU manage it's own data loading from the default data file.

We need to consider how we will package up the data and have the shipping versions of ChakraCore and Node-ChakraCore deal with this problem without having to have the user's environment set in a particular way.

/cc @digitalinfinity @jackhorton

**Comment by jackhorton** [comment] 2018-02-15 17:27
Dupe of #3800

**Closed by jackhorton** 2018-02-15 17:27 UTC
Labels: Intl-ICU, Task

**Comment by dilijev** [comment] 2018-02-17 01:12
^ Hah, funnily, I had thought that #3800 would be a small part of this and it looks to have evolved into the main concern.
