### ISSUE TITLE
Investigate static analysis findings from PVS

### ISSUE THREAD

**Issue by EdMaurer** [Microsoft/ChakraCore#180] opened 2016-01-22 17:02 UTC
This [blog](http://www.viva64.com/en/b/0370/) discusses a number of issues the PVS tool found. Some look like real bugs. Please investigate and fix or assign to the appropriate area expert.

**Comment by abchatra** [comment] 2016-01-22 18:10
This is duplicate of #177

**Closed by abchatra** 2016-01-22 18:10 UTC
