### ISSUE TITLE
 date.prototype.toLocaleString() return value contains U+200E chars with each date part

### ISSUE THREAD

**Issue by dangander-BESA** [Microsoft/ChakraCore#5847] opened 2018-11-26 14:40 UTC
Calling .slice() (or .substring()) on a string created by date.prototype.toLocaleString() returns unexpected results in Edge.

Repro:
```javascript
var date = new Date(2018, 11, 20)
var str = date.toLocaleString("en-GB")

console.log(str);
console.log(str.slice(0, 10));

var str2 = '20/12/2018, 00:00:00'
console.log(str2)
console.log(str2.slice(0, 10))
```

Expect console to output:
```
20/12/2018, 00:00:00
20/12/2018
20/12/2018, 00:00:00
20/12/2018
```

Edge produces:
```
20/12/2018, 00:00:00
20/12/
20/12/2018, 00:00:00
20/12/2018
```

Firefox + Chrome work as expected, untested in IE.

**Comment by zenparsing** [comment] 2018-11-26 17:07
It appears that CC is inserting `U+200E LEFT-TO-RIGHT MARK` (8206) into the resulting string.

```js
var s = new Date(2018, 11, 20).toLocaleString("en-US");
print([...s].map(s => s.charCodeAt(0)));
```

```
#### v8
49,50,47,50,48,47,50,48,49,56,44,32,49,50,58,48,48,58,48,48,32,65,77

#### sm
49,50,47,50,48,47,50,48,49,56,44,32,49,50,58,48,48,58,48,48,32,65,77

#### ch
8206,49,50,8206,47,8206,50,48,8206,47,8206,50,48,49,56,8206,32,8206,49,50,8206,58,8206,48,48,8206,58,8206,48,48,8206,32,8206,65,77
```

**Comment by dangander-BESA** [comment] 2018-11-27 10:16
good spot. Renamed the issue since it's not a slice / substring problem

**Comment by MSLaguana** [comment] 2018-11-27 16:55
I believe that this has come up before, e.g. https://github.com/Microsoft/ChakraCore/issues/3728

From what I understand, this is spec-compliant behavior, although surprising.

**Comment by dilijev** [comment] 2018-11-30 00:02
@dangander-BESA What version of Edge are you on?

@MSLaguana This has come up before numerous times. The move to ICU should have made this behavior match other implementations. 

/cc @jackhorton 

All WinGlob-versus-ICU compat issues are being tracked as part of #3644

**Comment by jackhorton** [comment] 2018-11-30 17:16
I can confirm that this is fixed in RS5 (Edge 44/EdgeHTML 18). For what its worth, I believe IE11 will experience the same issue, since it also used Windows Globalization for date formatting. Not sure about <= IE10.

RS5 also includes a new Intl.DateTimeFormat API, `Intl.DateTimeFormat.prototype.formatToParts`, which should be preferred when available for parsing date strings. This API is also available in recent versions of Chrome and Firefox (not sure about Safari). The output of `Date.prototype.toLocaleString` is highly implementation-dependent and subject to break at any time, so caution should be taken when trying to parse the resulting string.

**Closed by jackhorton** 2018-11-30 17:16 UTC
Labels: Bug, Compatibility, External, Severity: 2

**Comment by dangander-BESA** [comment] 2018-12-02 20:44
Thanks - been away from things for a couple of days so sorry @dilijev I missed requests for more info.
Thanks @jackhorton for update on the fix - take your point on avoiding string parsing. It usually is something I avoid - we stumbled on it by accident and the dev has since reworked things away from string manipulation to make it more reliable anyway, and luckily we don't need to support <IE11 anyway!
