### ISSUE TITLE
Exception stored on module record gets eaten

### ISSUE THREAD

**Issue by fatcerberus** [Microsoft/ChakraCore#3871] opened 2017-10-04 05:23 UTC
I'm trying to propagate exceptions caught during static module loading back to my event loop where they can be dealt with cleanly (by reporting them and then terminating).  In order to do that, I have the following logic in my module loader:

```c
JsModuleEvaluation(module_record, &result);
JsHasException(&have_error);
if (have_error) {
	JsGetAndClearException(&exception);  // don't want to throw here
	JsSetModuleHostInfo(module_record, JsModuleHostInfo_Exception, exception);
}
```

And later:
```c
JsGetModuleHostInfo(module, JsModuleHostInfo_Exception, &exception);
if (exception != JS_INVALID_REFERENCE)
	throw_value(exception);
```

However, `exception` always comes out as NULL in the latter code and nothing is thrown.  So as a followup I tried the following test:
```c
JsSetModuleHostInfo(module_record, JsModuleHostInfo_Exception, exception);
JsGetModuleHostInfo(module_record, JsModuleHostInfo_Exception, &exception);
```

`exception` goes into JsSetModuleHostInfo as a non-null reference and comes out of JsGetModuleHostInfo as NULL.  The exception is apparently getting eaten once I set it on the module record.

**Comment by akroshg** [comment] 2017-10-11 22:02
@fatcerberus did you verify that ```JsSetModuleHostInfo``` returns no error? 
@boingoing do you happen to know how ```JsModuleHostInfo_Exception``` supposed to work? I don't see native unittest with this flag so it is not obvious for me to understand.

**Comment by fatcerberus** [comment] 2017-10-11 22:35
I checked the return value, yes.  It returns JsNoError.

**Comment by fatcerberus** [comment] 2017-10-16 07:35
@akroshg Setting the exception flag puts the module record in an error state the same as if e.g. parsing led to a syntax error.  That part seems to work fine; the issue here is that I have no way to *get the exception back out* as it always reads back as nullptr no matter what.

**Comment by digitalinfinity** [comment] 2017-12-07 04:36
This looks like a bug in `JsSetModuleHostInfo`:
```
        case JsModuleHostInfo_Exception:
            moduleRecord->OnHostException(hostInfo);
            break;
```

It's likely that the module was parsed successfully and so you can't set an error on it. And indeed, `SourceTextModuleRecord::OnHostException` does return an error but it doesn't get propagated by `JsSetModuleHostInfo`

**Comment by fatcerberus** [comment] 2017-12-07 05:01
> It's likely that the module was parsed successfully and so you can't set an error on it. And indeed, SourceTextModuleRecord::OnHostException does return an error but it doesn't get propagated by JsSetModuleHostInfo

Hmm, possible.  But errors set in this way *do* seem to get propagated to JS code, e.g. by rejecting a promise returned by `import()`.  It's just that I can't read them back.

**Comment by digitalinfinity** [comment] 2017-12-08 01:47
That's odd and reading the code I'm not sure how that's possible. I think we should just fix the error propagation first and then see if the behavior you're seeing changes, and then proceed from there. @akroshg is out till the end of the year so I don't imagine we'll get to this till early next year but if you want to PR this, I'll be happy to help land it.

**Comment by akroshg** [comment] 2018-01-12 00:22
@fatcerberus apologize for not responding sooner. I wrote a simple test and it seems to work ok.
```cpp
    void SetModuleHostInfoTest(JsRuntimeAttributes attributes, JsRuntimeHandle runtime)
    {
        JsModuleRecord requestModule = JS_INVALID_REFERENCE;
        JsValueRef specifier = nullptr;

        REQUIRE(JsPointerToString(_u("mod1.js"), wcslen(_u("mod1.js")), &specifier) == JsNoError);
        REQUIRE(JsInitializeModuleRecord(nullptr, specifier, &requestModule) == JsNoError);
        JsValueRef error = nullptr, errorMsg = nullptr;
        REQUIRE(JsPointerToString(_u("test error"), wcslen(_u("test error")), &errorMsg) == JsNoError);
        REQUIRE(JsCreateError(errorMsg, &error) == JsNoError);

        REQUIRE(JsSetModuleHostInfo(requestModule, JsModuleHostInfo_Exception, error) == JsNoError);

        JsValueRef errorOut = nullptr;
        JsGetModuleHostInfo(requestModule, JsModuleHostInfo_Exception, &errorOut);
        REQUIRE(errorOut == error);
    }

``` 

having said that I still do not understand what is expected from JsModuleHostInfo_Exception, as there are not much documentation around in the code base. In this file we seem to force that it should be called before it is parsed.
```cpp
    HRESULT SourceTextModuleRecord::OnHostException(void* errorVar)
    {
        if (!RecyclableObject::Is(errorVar))
        {
            return E_INVALIDARG;
        }
        AssertMsg(!WasParsed(), "shouldn't be called after a module is parsed");
        if (WasParsed())
        {
            return E_INVALIDARG;
        }
        this->errorObject = errorVar;
```
This flag is not used by Edge, so I'd like @liminzhu @boingoing to comment what is expected behavior for this flag.

**Comment by akroshg** [comment] 2018-01-24 21:48
Part of the API is fixed. @fatcerberus can you see this fix the problem you have?

**Comment by akroshg** [comment] 2018-01-30 22:31
Closing this issue - as the API's return value is fixed.

**Closed by akroshg** 2018-01-30 22:31 UTC
Labels: Bug, Dev Experience, Severity: 1, good first issue, help wanted
