### ISSUE TITLE
[Unicode] Use Unicode 9’s `ID_Start` & `ID_Continue` for identifiers

### ISSUE THREAD

**Issue by mathiasbynens** [Microsoft/ChakraCore#1208] opened 2016-06-28 09:37 UTC
- Unicode 8 has 109,830 `ID_Start` symbols; Unicode 9 has 117,007, i.e. 7,177 more (no removals).
- Unicode 8 has 112,352 `ID_Continue` symbols; Unicode 9 has 119,691, i.e. 7,339 more (no removals).

E.g. these should not throw per Unicode 9:

``` js
Function('var \u{1E943}'); // new ID_Start
Function('var _\u{1E959}'); // new ID_Continue
```

I’ve attached a tarball containing `results.js` which contains the full list of new `ID_Start` and `ID_Continue` symbols in Unicode 9, and the Node.js script used to generate it.

[`unicode-9-identifiers.tar.gz`](https://github.com/Microsoft/ChakraCore/files/336677/unicode-9-identifiers.tar.gz)

---

See also:
- JavaScriptCore: https://bugs.webkit.org/show_bug.cgi?id=159203
- SpiderMonkey: https://bugzilla.mozilla.org/show_bug.cgi?id=1282724
- V8: https://bugs.chromium.org/p/v8/issues/detail?id=5155

**Comment by dilijev** [comment] 2016-06-28 21:27
I'll add that ECMA 2017 has a stipulation for which Unicode Standard version must be supported:

https://tc39.github.io/ecma262/#sec-conformance

> A conforming implementation of ECMAScript must interpret source text input in conformance with the Unicode Standard, Version 8.0.0 or later and ISO/IEC 10646.

No reason we couldn't add this but it's not a high priority under the current version of the spec.

@bterlson Does that seem like a fair assessment?

**Comment by mathiasbynens** [comment] 2016-06-29 06:36
The intent is to use the latest available Unicode version. See https://github.com/tc39/ecma262/pull/620 for some discussion. @bterlson Perhaps it would be clearer to merge that PR now, and then update to refer to the (version-less) _latest_ version in a future PR?

**Comment by bterlson** [comment] 2016-06-29 23:36
@mathiasbynens It's only a few weeks until we have the final consensus on version-less latest reference :) But I see your point. We should be tracking Unicode 9 at this point.

**Comment by dilijev** [comment] 2016-11-11 18:30
@bterlson I'm going ahead with this change, but just wanted to follow up about whether consensus was reached?

**Comment by dilijev** [comment] 2016-11-11 19:50
@mathiasbynens to clarify, I took your result script and added the following lines:

```js
console.log("number of new ID_Start symbols:    " + new_ID_Start.length);
console.log("number of new ID_Continue symbols: " + new_ID_Continue.length);
console.log(new_ID_Continue.length - new_ID_Start.length);
```

And see the following counts:

```
number of new ID_Start symbols:    7177
number of new ID_Continue symbols: 7339
162
```

That doesn't quite match with the numbers included in your original post. If I'm not mistaken, all ID_Start characters can be used as ID_Continue, but not all ID_Continue can be used as ID_Start. (If I understand correctly, ID_Continue could include numerals, which cannot be used as ID_Start.) It looks like the ES standard specifies using these Unicode character classes as they are.

(Side note: I find it interesting that it falls into the realm of the Unicode standard to define what characters can be used for identifiers, given that it seems like a language-specific implementation detail.)

**Comment by mathiasbynens** [comment] 2016-11-14 12:48
@dilijev The numbers I posted were wrong, indeed. The output produced by the script (and the numbers you logged) are correct. Here’s how I confirmed this:

```
> require('unicode-8.0.0/Binary_Property/ID_Start/code-points.js').length
109830

> require('unicode-9.0.0/Binary_Property/ID_Start/code-points.js').length
117007

> 117007 - 109830 // difference
7177

> require('unicode-8.0.0/Binary_Property/ID_Continue/code-points.js').length
112352

> require('unicode-9.0.0/Binary_Property/ID_Continue/code-points.js').length
119691

> 119691 - 112352 // difference
7339
```

I’ve updated the top post accordingly.

> (Side note: I find it interesting that it falls into the realm of the Unicode standard to define what characters can be used for identifiers, given that it seems like a language-specific implementation detail.)

Interestingly, ES5 defined a list of Unicode `General_Category` values whose characters were allowed in `IdentifierStart` and `IdentifierPart`. ES6 / ES2015 simplified by referring to `ID_Start` / `ID_Continue` instead.

**Comment by dilijev** [comment] 2016-11-15 00:46
Marking as External.

It looks like compliance with a particular Unicode version is an external library issue on all platforms.

On Windows we use
`ABI::Windows::Data::Text::IUnicodeCharactersStatics::IsIdStart`
`ABI::Windows::Data::Text::IUnicodeCharactersStatics::IsIdContinue`
(See `lib\Runtime\PlatformAgnostic\Platform\Windows\UnicodeText.cpp`)

For non-Windows we use ICU's `u_IsIDStart(ch)` and `u_hasBinaryProperty(ch, UCHAR_ID_CONTINUE)`.
(See `lib\Runtime\PlatformAgnostic\Platform\Linux\UnicodeText.ICU.cpp`)

**Comment by digitalinfinity** [comment] 2016-11-15 00:53
Note that the different external libraries have different levels of Unicode versions supported. IIRC, the ICU version we support supports Unicode 8? Last I checked, Windows.Globalization.dll supported Unicode 6.1 or 6.2, IIRC. cc @bterlson

**Comment by dilijev** [comment] 2016-11-15 01:13
Hmm in that case it might not be reasonable to wait for Windows to update their APIs for Unicode -- otherwise we just have to accept that Unicode compliance on Windows will lag behind.

Would it be reasonable to take a dependency on ICU for ChakraCore and/or Chakra to resolve this issue? (If we did that it would most likely be out of scope for milestone 1.4.)

**Comment by dilijev** [comment] 2016-11-15 01:19
Confirmed the test cases above do not work in node LTS Argon 6.9.1 but do work in node 7.1.0.
Confirmed they don't work in ch on Windows.
Confirmed they don't work in ch on Linux either (as @digitalinfinity mentioned, the ICU version we're using does not support Unicode 9).

**Comment by dilijev** [comment] 2016-11-15 22:00
Removing this from Milestone 1.4. If we wait for Windows to update the Unicode APIs, there's no action to take here. If we were to implement this functionality or change dependencies, it is too risky for this milestone.

**Comment by dilijev** [comment] 2016-11-16 00:19
TC39's intent is generally that the latest version of the Unicode standard should be used in the latest version of the ECMAScript standard. Removed "Pending TC39 Consensus" label.

**Comment by dilijev** [comment] 2017-07-11 22:27
Related #3271 #3050

**Comment by dilijev** [comment] 2017-09-05 18:00
Closing this issue as External: by current design these classifications are determined by calling APIs in external libraries.

We can open a new issue if we decide we want to embed the ID_START and ID_CONTINUE classifications of characters directly into ChakraCore.

**Closed by dilijev** 2017-09-05 18:00 UTC
Labels: Bug, External
