### ISSUE TITLE
Not using strict mode within ClassDeclaration statement

### ISSUE THREAD

**Issue by sunlili** [microsoft/ChakraCore#6365] opened 2019-12-24 09:12 UTC
The bug can be reproduced in ch version 1.11.15.0.

code:
```
class c extends(d = function() {
    return 0;
}, d) {};
```

ChakraCore print nothing, however, it should throw an error.

According to ecma-262
•	All parts of a ClassDeclaration or a ClassExpression are strict mode code.
•	In strict mode code, assignment to an undeclared identifier or otherwise unresolvable reference does not create a property in the global object. When a simple assignment occurs within strict mode code, its LeftHandSideExpression must not evaluate to an unresolvable Reference. If it does, a ReferenceError exception is thrown.
So, assignment to ‘d’, which is undeclared, should throw a ReferenceError exception.

ISec Lab
2019.12.24

**Comment by rhuanjl** [comment] 2020-03-25 16:56
This is a duplicate of #5367

**Closed by rhuanjl** 2020-03-25 16:56 UTC
