### ISSUE TITLE
Unknown empty character in string

### ISSUE THREAD

**Issue by rybon** [Microsoft/ChakraCore#3728] opened 2017-09-14 09:20 UTC
Edge 14 & 15 on Windows 10.

`var a = new Date().toLocaleTimeString('en-us', { timeZoneName: 'short' }).split(' ')[2].split('')[0];`

Inspecting `a` reports an empty string. But `a === ''` or `a == ''` reports `false`. What is going on here?

In my timezone, `var tz = new Date().toLocaleTimeString('en-us', { timeZoneName: 'short' }).split(' ')[2]` reports `CEST`, but `tz.length` reports `5`. This should obviously be `4`. I can get around this problem like so, but would rather not use this workaround at all:

```
var tzArray = tz.split('');
tz = tzArray.slice(1, tzArray.length).join('');
tz.length // reports 4
```

These problems don't happen in Chrome / Firefox / Safari / Opera.

**Comment by dilijev** [comment] 2017-09-14 20:18
It's a little unclear from the issue report, but you're almost certainly seeing BiDi marks (specifically left-to-right marks) which WinGlob uses to increase clarity of display in mixed-direction text.

```
var a = new Date().toLocaleTimeString('en-us', { timeZoneName: 'short' }).split(' ')[2].split('')[0];
a.codePointAt(0); // 8206
```

8206 is 0x200E

http://www.fileformat.info/info/unicode/char/200e/index.htm
Unicode Character 'LEFT-TO-RIGHT MARK' (U+200E)

Duplicate of #599

**Closed by dilijev** 2017-09-14 20:18 UTC
Labels: Needs Triage

**Comment by dilijev** [comment] 2017-09-14 20:19
Also related: there's an open bug about timeZoneName in ChakraCore.

https://github.com/Microsoft/ChakraCore/issues/3096

**Comment by dilijev** [comment] 2017-09-14 20:26
If you reduce the repro to remove that option and inspect the code points of the string that is produced, you can see the divergent behavior between Chakra and others.
(I also sanitized the BiDi markers before printing the string so you can easily see from the eshost output that the string is otherwise the same.)

```
>eshost -itsx "a = new Date().toLocaleString('en-us'); print(a.replace(/[^\w\s:/]/ig,'')); a.split('').forEach((x)=>print('0x'+x.codePointAt(0).toString(16)))"

## Source
a = new Date().toLocaleString('en-us'); print(a.replace(/[^\w\s:/]/ig,'')); a.split('').forEach((x)=>print('0x'+x.codePointAt(0).toString(16)))

┌──────────────────┬──────────────────────┐
│ d8               │ 9/14/2017 1:24:01 PM │
│ jsc              │ 0x39                 │
│ node             │ 0x2f                 │
│ sm               │ 0x31                 │
│                  │ 0x34                 │
│                  │ 0x2f                 │
│                  │ 0x32                 │
│                  │ 0x30                 │
│                  │ 0x31                 │
│                  │ 0x37                 │
│                  │ 0x2c                 │
│                  │ 0x20                 │
│                  │ 0x31                 │
│                  │ 0x3a                 │
│                  │ 0x32                 │
│                  │ 0x34                 │
│                  │ 0x3a                 │
│                  │ 0x30                 │
│                  │ 0x31                 │
│                  │ 0x20                 │
│                  │ 0x50                 │
│                  │ 0x4d                 │
├──────────────────┼──────────────────────┤
│ ch-1.7.1         │ 9/14/2017 1:24:01 PM │
│ ch-master-latest │ 0x200e               │
│ node-ch          │ 0x39                 │
│                  │ 0x200e               │
│                  │ 0x2f                 │
│                  │ 0x200e               │
│                  │ 0x31                 │
│                  │ 0x34                 │
│                  │ 0x200e               │
│                  │ 0x2f                 │
│                  │ 0x200e               │
│                  │ 0x32                 │
│                  │ 0x30                 │
│                  │ 0x31                 │
│                  │ 0x37                 │
│                  │ 0x200e               │
│                  │ 0x20                 │
│                  │ 0x200e               │
│                  │ 0x31                 │
│                  │ 0x200e               │
│                  │ 0x3a                 │
│                  │ 0x200e               │
│                  │ 0x32                 │
│                  │ 0x34                 │
│                  │ 0x200e               │
│                  │ 0x3a                 │
│                  │ 0x200e               │
│                  │ 0x30                 │
│                  │ 0x31                 │
│                  │ 0x200e               │
│                  │ 0x20                 │
│                  │ 0x200e               │
│                  │ 0x50                 │
│                  │ 0x4d                 │
└──────────────────┴──────────────────────┘
```

**Comment by dilijev** [comment] 2017-09-14 20:30
Please note that Intl-produced strings are intended to be opaque strings for display only, and are not meant to be parsed or broken apart in such a way. There are spec proposals in the works to add the ability to directly extract specific information to avoid this.

**Comment by rybon** [comment] 2017-09-15 08:37
@dilijev thanks for the response. I understand the problem a bit better now. I'll see if I can find a solution that avoids this problem altogether.
