### ISSUE TITLE
ChakraCore crashes with assertion failure in Scan.h:495

### ISSUE THREAD

**Issue by leeswimming** [Microsoft/ChakraCore#5571] opened 2018-08-04 06:37 UTC
Debug build of ChakraCore received SIGILL with an ASSERTION FAILURE.

```
$ ./build.sh --debug
$ ./out/Debug/ch test.js
ASSERTION 14607: (/data/ChakraCore/lib/Parser/Scan.h, line 495) static_cast<charcount_t>(m_pchMinTok - m_pchBase) >= m_cMinTokMultiUnits
 Failure: (static_cast<charcount_t>(m_pchMinTok - m_pchBase) >= m_cMinTokMultiUnits)
$ cat test.js
eval('\u20091a')
```

OS: Ubuntu 18.04 LTS
Arch: x86_64

**Comment by boingoing** [comment] 2018-08-14 22:40
Thank you for the report. I believe this is a dupe of https://microsoft.visualstudio.com/OS/_workitems/edit/17117705 which has been pretty hard to create a simple repro for. I am looking into it.

**Closed** 2018-08-15 23:58 UTC
