### ISSUE TITLE
Ensure parsing heuristics are producing desired outcome when given Closure-produced content

### ISSUE THREAD

**Issue by EdMaurer** [Microsoft/ChakraCore#2311] opened 2017-01-05 00:58 UTC
Also, possibly add some telemetry if there is a reasonable measure to report.

**Comment by toddreifsteck** [comment] 2017-01-09 18:04
Unsure if it is related to Closure-produced content but https://foxsports.com has ~1 second of parse/ByteCodeGen and only 650 ms of execution. It may be a good site to investigate.

**Comment by agarwal-sandeep** [comment] 2018-03-01 00:46
@pleath @boingoing do we understand what the issue is and how prevalent this is?

**Comment by pleath** [comment] 2018-03-01 01:01
It sounds like this is related to the several work items we have in the works to speed up the initial load. Can probably lose this issue (though it's nice that it calls out foxsports.com as a poster child).

**Comment by pleath** [comment] 2018-03-01 01:01
BTW, the IIFE issue was resolved in RS3 with the introduction of deferral of functions-in-block.

**Closed** 2018-03-01 01:32 UTC
Labels: Task
