### ISSUE TITLE
Crash [@ Js::AsmJsFunc::GetFncNode] involving "use asm"

### ISSUE THREAD

**Issue by nth10sd** [Microsoft/ChakraCore#2269] opened 2016-12-22 07:39 UTC
```
f = (function(stdlib, foreign, heap) {
    "use asm";
    return function() {};
    function f() {};
});
```

$ /home/skywinlinvm/chakracore/BuildLinux/Debug/ch test.js 
Segmentation fault (core dumped)

file /home/skywinlinvm/chakracore/BuildLinux/Debug/ch
/home/skywinlinvm/chakracore/BuildLinux/Debug/ch: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32

Git hash: 3769053
OS: Ubuntu Linux 16.04.1 LTS
Arch: x86_64

```
Thread 1 "ch" received signal SIGSEGV, Segmentation fault.
Js::AsmJsFunc::GetFncNode (this=0x0) at /home/skywinlinvm/chakracore/lib/Runtime/./Language/AsmJsTypes.h:756
756	        inline ParseNode* GetFncNode() const{ return mFncNode; }
(gdb) bt
#0  Js::AsmJsFunc::GetFncNode (this=0x0) at /home/skywinlinvm/chakracore/lib/Runtime/./Language/AsmJsTypes.h:756
#1  0x00007ffff54bf35a in Js::AsmJsModuleCompiler::CompileFunction (this=0x7fffffffbb68, func=0x0, funcIndex=0) at /home/skywinlinvm/chakracore/lib/Runtime/Language/AsmJsModule.cpp:587
#2  0x00007ffff54bf2c7 in Js::AsmJsModuleCompiler::CompileAllFunctions (this=0x7fffffffbb68) at /home/skywinlinvm/chakracore/lib/Runtime/Language/AsmJsModule.cpp:33
#3  0x00007ffff547f548 in Js::AsmJSCompiler::CheckModule (cx=0x7fffffffc198, parser=@0x7fffffffc0d8: 0x7ff7f16a64c0, stmtList=0x7ff7f16a56f0) at /home/skywinlinvm/chakracore/lib/Runtime/Language/AsmJs.cpp:1169
#4  0x00007ffff547f7a8 in Js::AsmJSCompiler::Compile (cx=0x7fffffffc198, parser=0x7ff7f16a64c0, stmtList=0x7ff7f16a56f0) at /home/skywinlinvm/chakracore/lib/Runtime/Language/AsmJs.cpp:1212
#5  0x00007ffff52734f0 in ByteCodeGenerator::EmitScopeList (this=0x7fffffffc5d0, pnode=0x7ff7f16a5270, breakOnBodyScopeNode=0x0) at /home/skywinlinvm/chakracore/lib/Runtime/ByteCode/ByteCodeEmitter.cpp:3616
#6  0x00007ffff52737e3 in ByteCodeGenerator::EmitScopeList (this=0x7fffffffc5d0, pnode=0x7ff7f16a5160, breakOnBodyScopeNode=0x0) at /home/skywinlinvm/chakracore/lib/Runtime/ByteCode/ByteCodeEmitter.cpp:3679
#7  0x00007ffff527369f in ByteCodeGenerator::EmitScopeList (this=0x7fffffffc5d0, pnode=0x7ff7f16a5030, breakOnBodyScopeNode=0x0) at /home/skywinlinvm/chakracore/lib/Runtime/ByteCode/ByteCodeEmitter.cpp:3665
#8  0x00007ffff52733df in ByteCodeGenerator::EmitProgram (this=0x7fffffffc5d0, pnodeProg=0x7ff7f16a5030) at /home/skywinlinvm/chakracore/lib/Runtime/ByteCode/ByteCodeEmitter.cpp:2759
#9  0x00007ffff52a7f85 in ByteCodeGenerator::Generate (pnode=0x7ff7f16a5030, grfscr=4096, byteCodeGenerator=0x7fffffffc5d0, ppRootFunc=0x7fffffffc880, sourceIndex=0, forceNoNative=false, parser=0x7fffffffca00, functionRef=0x0) at /home/skywinlinvm/chakracore/lib/Runtime/ByteCode/ByteCodeGenerator.cpp:1883
#10 0x00007ffff52abba1 in GenerateByteCode (pnode=0x7ff7f16a5030, grfscr=4096, scriptContext=0x55555590b460, ppRootFunc=0x7fffffffc880, sourceIndex=0, forceNoNative=false, parser=0x7fffffffca00, pse=0x7fffffffd1a0, parentScopeInfo=0x0, functionRef=0x0) at /home/skywinlinvm/chakracore/lib/Runtime/ByteCode/ByteCodeGenerator.cpp:2068
#11 0x00007ffff51a5939 in Js::ScriptContext::GenerateRootFunction (this=0x55555590b460, parseTree=0x7ff7f16a5030, sourceIndex=0, parser=0x7fffffffca00, grfscr=4096, pse=0x7fffffffd1a0, rootDisplayName=0x7ffff5e8d2f0 <Js::Constants::GlobalCode> u"Global code") at /home/skywinlinvm/chakracore/lib/Runtime/Base/ScriptContext.cpp:1943
#12 0x00007ffff51a5429 in Js::ScriptContext::LoadScript (this=0x55555590b460, script=0x5555558d5eb0 "f = (function(stdlib, foreign, heap) {\n    \"use asm\";\n    return function() {};\n    function f() {};\n});", cb=104, pSrcInfo=0x7fffffffce60, pse=0x7fffffffd1a0, ppSourceInfo=0x7fffffffce58, rootDisplayName=0x7ffff5e8d2f0 <Js::Constants::GlobalCode> u"Global code", loadScriptFlag=(LoadScriptFlag_Utf8Source | LoadScriptFlag_ExternalArrayBuffer), scriptSource=0x7ff7f1f30050) at /home/skywinlinvm/chakracore/lib/Runtime/Base/ScriptContext.cpp:1897
#13 0x00007ffff4bd02d5 in RunScriptCore(void*, unsigned char const*, unsigned long, LoadScriptFlag, unsigned long, char16_t const*, bool, _JsParseScriptAttributes, bool, void**)::$_73::operator()(Js::ScriptContext*, TTD::TTDJsRTActionResultAutoRecorder&) const (this=0x7fffffffd0a0, scriptContext=0x55555590b460, _actionEntryPopper=...) at /home/skywinlinvm/chakracore/lib/Jsrt/Jsrt.cpp:2928
#14 0x00007ffff4bcffc7 in _JsErrorCode ContextAPINoScriptWrapper<RunScriptCore(void*, unsigned char const*, unsigned long, LoadScriptFlag, unsigned long, char16_t const*, bool, _JsParseScriptAttributes, bool, void**)::$_73>(RunScriptCore(void*, unsigned char const*, unsigned long, LoadScriptFlag, unsigned long, char16_t const*, bool, _JsParseScriptAttributes, bool, void**)::$_73, bool, bool)::{lambda(Js::ScriptContext*)#1}::operator()(Js::ScriptContext*) const (this=0x7fffffffd028, scriptContext=0x55555590b460) at /home/skywinlinvm/chakracore/lib/Jsrt/JsrtInternal.h:293
#15 0x00007ffff4bcf8cd in ContextAPINoScriptWrapper_Core<_JsErrorCode ContextAPINoScriptWrapper<RunScriptCore(void*, unsigned char const*, unsigned long, LoadScriptFlag, unsigned long, char16_t const*, bool, _JsParseScriptAttributes, bool, void**)::$_73>(RunScriptCore(void*, unsigned char const*, unsigned long, LoadScriptFlag, unsigned long, char16_t const*, bool, _JsParseScriptAttributes, bool, void**)::$_73, bool, bool)::{lambda(Js::ScriptContext*)#1}>(_JsErrorCode ContextAPINoScriptWrapper<RunScriptCore(void*, unsigned char const*, unsigned long, LoadScriptFlag, unsigned long, char16_t const*, bool, _JsParseScriptAttributes, bool, void**)::$_73>(RunScriptCore(void*, unsigned char const*, unsigned long, LoadScriptFlag, unsigned long, char16_t const*, bool, _JsParseScriptAttributes, bool, void**)::$_73, bool, bool)::{lambda(Js::ScriptContext*)#1}, bool, bool) (fn=..., allowInObjectBeforeCollectCallback=false, scriptExceptionAllowed=false) at /home/skywinlinvm/chakracore/lib/Jsrt/JsrtInternal.h:254
#16 0x00007ffff4ba47d8 in ContextAPINoScriptWrapper<RunScriptCore(void*, unsigned char const*, unsigned long, LoadScriptFlag, unsigned long, char16_t const*, bool, _JsParseScriptAttributes, bool, void**)::$_73>(RunScriptCore(void*, unsigned char const*, unsigned long, LoadScriptFlag, unsigned long, char16_t const*, bool, _JsParseScriptAttributes, bool, void**)::$_73, bool, bool) (fn=..., allowInObjectBeforeCollectCallback=false, scriptExceptionAllowed=false) at /home/skywinlinvm/chakracore/lib/Jsrt/JsrtInternal.h:291
#17 0x00007ffff4ba4689 in RunScriptCore (scriptSource=0x7ff7f1f30050, script=0x5555558d5eb0 "f = (function(stdlib, foreign, heap) {\n    \"use asm\";\n    return function() {};\n    function f() {};\n});", cb=104, loadScriptFlag=(LoadScriptFlag_Utf8Source | LoadScriptFlag_ExternalArrayBuffer), sourceContext=0, sourceUrl=0x7ff7f16a0000 u"/home/skywinlinvm/chakracoretest/bb18.js", parseOnly=false, parseAttributes=JsParseScriptAttributeNone, isSourceModule=false, result=0x0) at /home/skywinlinvm/chakracore/lib/Jsrt/Jsrt.cpp:2877
#18 0x00007ffff4ba72ce in CompileRun (scriptVal=0x7ff7f1f30050, sourceContext=0, sourceUrl=0x7ff7f1f09020, parseAttributes=JsParseScriptAttributeNone, result=0x0, parseOnly=false) at /home/skywinlinvm/chakracore/lib/Jsrt/Jsrt.cpp:4336
#19 JsRun (scriptVal=0x7ff7f1f30050, sourceContext=0, sourceUrl=0x7ff7f1f09020, parseAttributes=JsParseScriptAttributeNone, result=0x0) at /home/skywinlinvm/chakracore/lib/Jsrt/Jsrt.cpp:4358
#20 0x000055555555eafe in ChakraRTInterface::JsRun (script=0x7ff7f1f30050, sourceContext=0, sourceUrl=0x7ff7f1f09020, parseAttributes=JsParseScriptAttributeNone, result=0x0) at /home/skywinlinvm/chakracore/bin/ch/ChakraRtInterface.h:367
#21 0x000055555555ca92 in RunScript (fileName=0x5555558d5e90 "bb18.js", fileContents=0x5555558d5eb0 "f = (function(stdlib, foreign, heap) {\n    \"use asm\";\n    return function() {};\n    function f() {};\n});", bufferValue=0x0, fullPath=0x7fffffffd990 "/home/skywinlinvm/chakracoretest/bb18.js") at /home/skywinlinvm/chakracore/bin/ch/ch.cpp:321
#22 0x000055555555deb0 in ExecuteTest (fileName=0x5555558d5e90 "bb18.js") at /home/skywinlinvm/chakracore/bin/ch/ch.cpp:594
#23 0x000055555555dfb0 in ExecuteTestWithMemoryCheck (fileName=0x5555558d5e90 "bb18.js") at /home/skywinlinvm/chakracore/bin/ch/ch.cpp:642
#24 0x000055555555e4f0 in main (argc=2, c_argv=0x7fffffffdd08) at /home/skywinlinvm/chakracore/bin/ch/ch.cpp:869
(gdb)
```

**Comment by obastemur** [comment] 2016-12-22 16:52
Duplicate of #2270 . Closing this one

**Closed** 2016-12-22 16:52 UTC
