### ISSUE TITLE
Legacy builds failing on illegal sizeof

### ISSUE THREAD

**Issue by Penguinwizzard** [Microsoft/ChakraCore#2163] opened 2016-12-07 20:33 UTC
Legacy builds are failing with the following error:

D:\j\workspace\daily_dev12_x---55cdd258\lib\Runtime\Library\WebAssemblyTable.cpp(124): error C2070: 'unknown': illegal sizeof operand [D:\j\workspace\daily_dev12_x---55cdd258\lib\Runtime\Library\Chakra.Runtime.Library.vcxproj]

Assigning as per last person to change the line, but PRs welcome.

**Comment by dilijev** [comment] 2016-12-09 23:37
Duplicate of #2026.
Fixed by #1990, which revealed other issues and therefore hasn't been merged yet.

**Closed by dilijev** 2016-12-09 23:37 UTC
Labels: Build Break, Duplicate
