### ISSUE TITLE
Non-enumerable property is enumerable under certain conditions

### ISSUE THREAD

**Issue by Mosho1** [Microsoft/ChakraCore#5382] opened 2018-06-28 17:34 UTC
If the object has 128 keys that include dashes, then the non-enumerable property will be enumerable (also writable, configurable).

Tested on Edge 42.17134.1.0

```javascript
const test = (length = 128) => {
    let data = {};
    for (let i = 0; i < length; i++) {
        data[i + '-'] = true;
    }
    
    Object.defineProperty(data, 'nonEnumerable', {enumerable: false});

    return Object.getOwnPropertyDescriptor(data, 'nonEnumerable');
};
```

https://jsfiddle.net/q690m7w8/

**Comment by MSLaguana** [comment] 2018-06-28 17:53
What version of chakracore are you using here? I don't see this reproduce in latest master.

**Comment by Mosho1** [comment] 2018-06-28 18:05
I tested it in Edge itself. The Edge issue tracker points to this repo to JS engine related issues.

**Comment by MSLaguana** [comment] 2018-06-28 18:06
Ah ok. Looks like it should be fixed in a future release then :)

**Comment by Mosho1** [comment] 2018-06-28 18:07
I see, thanks!

**Comment by jackhorton** [comment] 2018-06-28 18:09
@MSLaguana I am reproing this on 17704...

**Comment by jackhorton** [comment] 2018-06-28 18:17
Oops, that's because the fix is new enough that it hasn't hit windows at all yet. This works properly on the tip of release/1.10.

**Closed by jackhorton** 2018-06-28 18:17 UTC
