### ISSUE TITLE
modify data attribute dynamically of object tag not working

### ISSUE THREAD

**Issue by DanielZanelatto** [Microsoft/ChakraCore#903] opened 2016-05-01 02:58 UTC
```HTML
<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <meta charset="utf-8" />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>
        <script>
            $(document).ready(function () {
                $('#doc').prop('data', 'anotherDocument.pdf');
            });
        </script>
    </head>
    <body>
        <object id="doc" type="application/pdf" data="document.pdf" width="500px" height="500px"></object>
    </body>
</html>
```

**Comment by DanielZanelatto** [comment] 2016-05-01 03:03
PDF is not replaced.

**Comment by dilijev** [comment] 2016-05-02 22:39
What browser are you using? It does the right thing for me in Edge (Windows 10: 10586.218), Chrome Canary, and Firefox Nightly.

(Where "the right thing" is: It loads the page and then changes the data attribute of the PDF object. You can observe the change in the DOM explorer or equivalent in the F12 console on any browser.)

I've tagged this as External and closing as NoRepro because I can't repro in Edge and this appears to be more of a web browser issue, if it can repro at all, than it is an issue with the ChakraCore engine.

**Comment by dilijev** [comment] 2016-05-02 22:41
For the moment I'll leave it open in case you can provide more info that helps us reproduce the issue.

Preferably, can you try to identify and reproduce an issue with the ChakraCore engine itself? If not, any information you can provide to help us track down any potential issue would be appreciated.

**Comment by dilijev** [comment] 2016-05-04 20:37
Closing as we can't repro and there's no action to take.

**Closed** 2016-05-04 22:57 UTC
Labels: External, Needs More Info, NoRepro

**Comment by jhasselkus** [comment] 2016-08-05 22:15
Here's a simple example that reproduces the problem on Edge 38.14393.0.0, EdgeHTML 14.14393:

[Plunkr](http://plnkr.co/edit/2zg4JuXIF3Gjf8QDNTpk?p=preview)

```html
<!DOCTYPE html>
<html>
  <head>
    <script data-require="jquery@*" data-semver="3.0.0" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.js"></script>
    <script>
        $(document).ready(function () {
          $('#pdfObj').prop('data', 'http://www.pdf995.com/samples/pdf.pdf');
        });
    </script>
  </head>
  <body>
    <h1>PDF viewer</h1>
      <object id="pdfObj" data="" type="application/pdf" width="500px" height="500px">
        <p>This browser doesn't support object</p>
      </object>
  </body>
</html>
```

The Plunkr properly displays the PDF file on Chrome and FF, but on Edge the object element stays blank.

**Comment by dilijev** [comment] 2016-08-05 22:19
@jhasselkus Oh hey, PDF995 is a blast from the past.

Yes, I can confirm the repro in Edge. However, this is not a JS issue, but rather an issue with Edge. Could you submit your issue here? https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/

**Comment by jhasselkus** [comment] 2016-08-05 22:25
@dilijev Understood -- will do. PDF995 was just the best sample file I could find :)

**Comment by dilijev** [comment] 2016-08-05 22:51
@jhasselkus By the way, for the Javascript and DOM manipulation part of this repro, it seems to work. If you put a breakpoint on the statement that changes the data attribute and then look at the DOM Explorer, you can see that the data property has not been set to the PDF, and then if you step over that statement and look at the DOM again, you can see that the property has been updated.

Therefore, I believe that this problem is related to the "application/pdf" object type.

**Comment by dilijev** [comment] 2016-11-15 22:07
Duplicate of #881
