### ISSUE TITLE
typedarray UT timeouts

### ISSUE THREAD

**Issue by MikeHolman** [Microsoft/ChakraCore#2945] opened 2017-05-09 02:55 UTC
I'm seeing that some typedarray UTs are often timing out, especially on OSX (e.g. test/typedarray/Int8Array2.js). @Penguinwizzard and I looked at this and we are hitting infinite bailout/rejit issue.

@pleath I believe this is related to your change to handle conversion of src operand on store to a typed array. In case we are storing a LikelyString into a typed array, we will bailout every time and keep rejitting the same code.

**Comment by pleath** [comment] 2017-05-17 21:50
The bailout is caused by conversion of a value we're storing to a type array. The bailout kind on the StElemI_A forces us to bailout instead of calling a helper to do the conversion. But the interpreter doesn't look at the value when it's updating profile info to show that a helper call was made. So the JIT keeps emitting the same code.

**Comment by pleath** [comment] 2017-05-18 23:24
Resolved by https://github.com/Microsoft/ChakraCore/pull/2991.

**Closed** 2017-05-18 23:25 UTC
Labels: Performance, Test Bug
