### ISSUE TITLE
Implement Promise.prototype.finally

### ISSUE THREAD

**Issue by ljharb** [Microsoft/ChakraCore#3520] opened 2017-08-12 17:10 UTC
Promise.prototype.finally is stage 3 - time to implement it! :-D

Test262 tests are merged.

Spec is [here](https://tc39.github.io/proposal-promise-finally/).

- https://github.com/tc39/proposal-promise-finally/issues/18

**Comment by ljharb** [comment] 2017-09-28 20:53
This is stage 3, and I'm hoping to seek stage 4 in November or January; any update on this?

**Comment by dilijev** [comment] 2017-09-29 03:45
This work is tentatively planned for the near future if we can fit it in. Earliest we can begin work on it is late October / early November.

**Comment by ljharb** [comment] 2017-11-09 23:16
@dilijev early November is here!

**Comment by dilijev** [comment] 2017-11-10 18:33
@ljharb Unfortunately, this didn't make the cut for our feature work on the upcoming release. We'll re-evaluate priorities and see when we can tackle this work item.

**Comment by ljharb** [comment] 2017-11-10 18:47
@dilijev please note that I'm seeking stage 4 for it in 3 weeks; if it doesn't make it then, I'd expect it to do so in January.

**Comment by dilijev** [comment] 2017-11-10 22:28
@ljharb at this point, it will not make it into the next Windows/Edge release. Best case the feature could be checked in to ChakraCore master and/or Node-ChakraCore, but we can't commit to anything at the moment.

**Comment by ljharb** [comment] 2017-11-11 03:25
It already has the requisite two (three, now) implementations; i was just hoping it could hit stage 4 with all 4 browsers - as is, it seems like edge will be the last to implement it.

**Comment by rhuanjl** [comment] 2018-01-29 21:06
Is anyone working on this? If not I'd like to have a stab at making a PR for it.

**Comment by ljharb** [comment] 2018-01-29 21:07
This is now stage 4, so it'd be great to get it implemented ASAP!

**Comment by dilijev** [comment] 2018-01-30 00:53
@rhuanjl AFAIK no one is currently working on this. Feel free to take a stab at it.

**Comment by rhuanjl** [comment] 2018-01-30 01:07
OK, will take me at least a week, maybe two, I'll use this comment as a tracker and post here if for any reason I don't think I can do it, please let me know at any point if it's being picked up internally (i.e. if I should drop it).
Todo prior to opening a PR:
- [ ] have ChakraCore recognise Promise.prototype.finally
- [ ] implement function behind it
- [ ] test using test262 test cases
- [ ] revise as necessary until all tests passed
- [ ] add appropriate test cases to CC CI tests

**Comment by dilijev** [comment] 2018-01-30 03:15
@rhuanjl test262 test cases may fail for reasons unrelated to this work (we unfortunately have thousands of test262 failures that we're tracking, probably not thousands of individual root causes). Use your best judgment but you don't have to block on test262.

**Comment by rhuanjl** [comment] 2018-01-30 19:44
@dilijev thanks for the heads up - I'll do the best I can for spec conformance and passing the tests that relate to this.
@ljharb just to double check I'm reading this right because it seems strange to me, please could you confirm that the below is correct, based on step 5 of the spec:
```js
let foo = Promise.reject("reason").finally("nothing here").catch(()=>{console.log("caught")});
```
Would **not** log "caught".

BUT based on step 6 and the definition of CatchFinally
```js
let foo = Promise.reject("reason").finally(()=>{}).catch(()=>{console.log("caught")});
```
Would log "caught".

**Comment by rhuanjl** [comment] 2018-01-30 19:46
dilijev thanks for the heads up I'll do the best I can for spec conformance and passing the relevant tests.

**Closed** 2018-02-15 21:53 UTC
Labels: ES Spec Changed, Feature Request, Proposal
