### ISSUE TITLE
ES2015, Cannot subclass Comment

### ISSUE THREAD

**Issue by beauceant** [Microsoft/ChakraCore#2999] opened 2017-05-19 19:25 UTC
Not able to extend Node types. Got a runtime crash when calling the parent constructor (`super()`)

```javascript
class SubNode extends Node {
     constructor() {
         super(); //<- breaks here: "invalid use of the super keyword"
     }
}

class SubComment extends Comment{
     constructor() {
         super(); //<- breaks here: "invalid use of the super keyword"
     }
}
```

**Comment by dilijev** [comment] 2017-05-20 01:32
@beauceant Which version of Edge are you using? I don't see this particular error in Windows 10 Creator's Update; it might be from an older version of Edge. @tcare and I suspect this is an Edge bug, but we'd like to get more information to confirm. /cc @suwc

For context see the following documentation on these Web APIs:
* https://developer.mozilla.org/en-US/docs/Web/API/Node
* https://developer.mozilla.org/en-US/docs/Web/API/Comment

In any case there might be a new bug here. This is a problem with a class provided by Edge, so you should [file a bug on Edge](https://github.com/Microsoft/ChakraCore/wiki/External-Issues#edge-issues) (and paste the link to that bug back here).

First I checked whether we should be able to construct `Node`. It looks like we cannot.

```js
try { console.log(new Node()); } catch (e) { console.log('' + e); }
// I'll refer to the result in the following three lines as MISSING_CONSTRUCTOR
// fails in Chrome:  "TypeError: Illegal constructor"
// fails in Edge:    "TypeError: Function expected"
// fails in Firefox: "TypeError: Illegal constructor."
```

The cause of the failures above are the same in each browser (although arguably our error message is the most unhelpful). `Node` does not have a constructor and so an instance cannot be constructed.

However, it looks like there is a bug with constructing `Node` subclasses like `Comment`:

```js
// The below two lines should be equivalent
// These lines fail in Edge with "Function expected"; passes in Chrome and Firefox.
new Comment("hello");
new Comment.prototype.constructor("hello");
```

It is possible to create a `Comment` using `document.createComment` (and similarly for other subclasses of `Node`):

```js
document.createComment("Hello") instanceof Comment; // true (all browsers)
```

More on the point of this Issue:

Creating class `SubNode` works. However, creating an **instance** of `SubNode` should fail because there is no `super` constructor to call.

```js
{ 
    class SubNode extends Node {
        constructor() {
            super(); // should fail because there is no super constructor to call.
        }
    }
    // class SubNode was created
    console.log(SubNode);
    // let x = new SubNode(); // fails with MISSING_CONSTRUCTOR as above
    // console.log(x);
}
```

The following result is related to not being able to construct `Comment` (and other `Node` subclasses):

```js
{ 
    class SubComment extends Comment {
        constructor() {
            super();
        }
    }
    // class SubComment was created
    console.log(SubComment);
    // let x = new SubComment(); // fails in Edge with MISSING_CONSTRUCTOR, passes in all others. 
    // console.log(x);
}
```

**Comment by beauceant** [comment] 2017-05-20 04:27
Thanks @dilijev ,
(Microsoft Edge 38.14393.1066.0) Sorry for the sloppy last-second addition of the Node constructor call to this thread, I actually experienced the Comment subclassing issue during the development. 
I can see the Comment constructor being experimental feature https://developer.mozilla.org/en-US/docs/Web/API/Comment/Comment. However, works on Chrome, Firefox and Opera, and satisfied my need of a customized inert Node implementation.

**Comment by dilijev** [comment] 2017-05-22 18:37
@beauceant Since this bug is a problem with a class provided by Edge, so we'd like to ask you to [file a bug on Edge](https://github.com/Microsoft/ChakraCore/wiki/External-Issues#edge-issues), and paste the link to that bug back here. Thanks!

**Comment by beauceant** [comment] 2017-05-22 19:01
Sure, it's already [here](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12080908).

**Comment by dilijev** [comment] 2017-05-22 19:12
@beauceant Thanks!

**Comment by curtisman** [comment] 2017-07-21 14:35
Closing as this is not a ChakraCore issue.

**Closed by curtisman** 2017-07-21 14:35 UTC
Labels: Bug, External
